Repository jesseduffield/lazygit, pull requests merged in 2023-09, with the labels that each got.

#2868 Add support for external diff commands (e.g. difftastic)
  docs/Custom_Pagers.md
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
  pkg/commands/git_commands/git_command_builder.go
  pkg/commands/git_commands/working_tree.go
  pkg/commands/git_commands/working_tree_test.go
  pkg/config/user_config.go
Labels: enhancement

#2940 Support to reset the current branch to a selected branch upstream
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/gui/controllers/branches_controller.go
  pkg/i18n/english.go
  pkg/i18n/korean.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/integration/tests/branch/reset_to_upstream.go
  pkg/integration/tests/branch/reset_upstream.go
  pkg/integration/tests/branch/set_upstream.go
  pkg/integration/tests/branch/show_divergence_from_upstream.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2990 Replace whitespace with '-' when renaming a branch
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/integration/tests/branch/rename.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2993 Add jump-to-panel label config setting
  docs/Config.md
  go.mod
  go.sum
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/sub_commits_helper.go
  pkg/gui/controllers/remotes_controller.go
  pkg/gui/controllers/switch_to_diff_files_controller.go
  pkg/gui/views.go
  vendor/github.com/go-errors/errors/README.md
  vendor/github.com/go-errors/errors/error_1_13.go
  vendor/github.com/go-errors/errors/error_backward.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/text/unicode/norm/trie.go
  vendor/modules.txt
Labels: enhancement

#2912 Add co-author to commits
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/rebase.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/commit/add_co_author.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2998 Change the default of the "gui.borders" config to "rounded"
  docs/Config.md
  pkg/config/user_config.go
Labels: enhancement

#3000 Various debugging improvements
  .vscode/launch.json
  Makefile
  cmd/integration_test/main.go
  go.mod
  go.sum
  pkg/integration/README.md
  pkg/integration/clients/cli.go
  pkg/integration/clients/go_test.go
  pkg/integration/clients/injector/main.go
  pkg/integration/clients/tui.go
  pkg/integration/components/runner.go
  vendor/github.com/mitchellh/go-ps/.gitignore
  vendor/github.com/mitchellh/go-ps/LICENSE.md
  vendor/github.com/mitchellh/go-ps/README.md
  vendor/github.com/mitchellh/go-ps/Vagrantfile
  vendor/github.com/mitchellh/go-ps/process.go
  vendor/github.com/mitchellh/go-ps/process_darwin.go
  vendor/github.com/mitchellh/go-ps/process_freebsd.go
  vendor/github.com/mitchellh/go-ps/process_linux.go
  vendor/github.com/mitchellh/go-ps/process_solaris.go
  vendor/github.com/mitchellh/go-ps/process_unix.go
  vendor/github.com/mitchellh/go-ps/process_windows.go
  vendor/modules.txt
Labels: maintenance

#3007 Use `Error` method to handle commits url copy from unknown service
  pkg/gui/controllers/basic_commits_controller.go
Labels: bug

#3012 Rename `test/results` to `test/_results`
  .gitignore
  pkg/integration/README.md
  pkg/integration/clients/tui.go
  pkg/integration/components/paths.go
  pkg/integration/components/runner.go
Labels: maintenance

#2992 Add a DisabledReason mechanism for menu items and keybindings
  pkg/gui/context/menu_context.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/cherry_pick_helper.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/menu_controller.go
  pkg/gui/controllers/options_menu_action.go
  pkg/gui/gui_common.go
  pkg/gui/keybindings.go
  pkg/gui/types/common.go
  pkg/gui/types/keybindings.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/reset_to_upstream.go
Labels: enhancement

#3013 Allow cherry-picking commits during a rebase
  pkg/commands/git_commands/rebase.go
  pkg/commands/git_commands/status.go
  pkg/gui/controllers/helpers/cherry_pick_helper.go
  pkg/integration/tests/cherry_pick/cherry_pick_during_rebase.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2877 Add history for search view
  pkg/gui/context/filtered_list_view_model.go
  pkg/gui/context/history_trait.go
  pkg/gui/context/remotes_context.go
  pkg/gui/context/search_trait.go
  pkg/gui/controllers/helpers/search_helper.go
  pkg/gui/controllers/search_prompt_controller.go
  pkg/gui/types/context.go
  pkg/gui/types/search_state.go
  pkg/integration/tests/filter_and_search/filter_search_history.go
  pkg/integration/tests/test_list.go
  pkg/utils/history_buffer.go
  pkg/utils/history_buffer_test.go
Labels: enhancement

#2973 Replace loader panels with waiting status (pull/push/fetch)
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/app_status_helper.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/sync_controller.go
  pkg/gui/gui.go
  pkg/gui/popup/fake_popup_handler.go
  pkg/gui/popup/popup_handler.go
  pkg/gui/types/common.go
  pkg/i18n/chinese.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/japanese.go
  pkg/i18n/korean.go
  pkg/i18n/polish.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/utils/utils.go
Labels: enhancement

#3020 Add menu to rebase onto selected branch remote upstream
  pkg/gui/controllers/branches_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/rebase_to_upstream.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2693 Use upstream branch when opening pull requests
  pkg/gui/controllers/branches_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/open_pull_request_no_upstream.go
  pkg/integration/tests/test_list.go
Labels: bug

#3022 Fix issue where active search inappropriately changed selected line
  go.mod
  go.sum
  pkg/gui/context/search_trait.go
  pkg/gui/controllers/helpers/search_helper.go
  pkg/gui/types/context.go
  pkg/integration/tests/filter_and_search/new_search.go
  pkg/integration/tests/test_list.go
  vendor/github.com/go-errors/errors/README.md
  vendor/github.com/go-errors/errors/error_1_13.go
  vendor/github.com/go-errors/errors/join_unwrap_1_20.go
  vendor/github.com/go-errors/errors/join_unwrap_backward.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: bug

#3019 Support passing -race flag to integration tests
  Makefile
  cmd/integration_test/main.go
  pkg/integration/clients/cli.go
  pkg/integration/clients/go_test.go
  pkg/integration/clients/tui.go
  pkg/integration/components/runner.go
Labels: maintenance

#3024 Respect $GIT_WORK_TREE and $GIT_DIR env vars (fix #3010).
  pkg/app/entry_point.go
Labels: bug

#3029 Improve debugging of integration tests
  pkg/gui/gui.go
  pkg/gui/test_mode.go
  pkg/integration/clients/injector/main.go
  pkg/integration/components/runner.go
Labels: maintenance

#3035 Use go:generate for cheatsheet
  .github/workflows/ci.yml
  Makefile
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/cheatsheet/check.go
  pkg/cheatsheet/generate.go
  pkg/cheatsheet/generator.go
  pkg/integration/tests/test_list_generator.go
  scripts/cheatsheet/main.go
Labels: maintenance

#3028 Change Makefile to build non-optimized
  Makefile
Labels: maintenance

#3040 Add comments in user config struct
  .golangci.yml
  pkg/config/user_config.go
Labels: docs

#3041 Update PR template to use go generate command
  .github/pull_request_template.md
  .vscode/settings.json
Labels: maintenance
