Repository jesseduffield/lazygit, pull requests merged in 2023-12, with the labels that each got.

#3046 commmit - enhance docs for keybinding 'c' for local branch
  docs/keybindings/Keybindings_en.md
  pkg/i18n/english.go
Labels: docs, requires-maintainer-signoff

#3101 fixed typo in test description
  pkg/integration/tests/misc/recent_repos_on_launch.go
Labels: requires-maintainer-signoff

#3039 Add UserConfig jsonschema generation script
  go.mod
  go.sum
  pkg/commands/git_commands/config.go
  pkg/config/user_config.go
  pkg/jsonschema/generate.go
  pkg/jsonschema/generator.go
  schema/config.json
  vendor/github.com/bahlo/generic-list-go/LICENSE
  vendor/github.com/bahlo/generic-list-go/README.md
  vendor/github.com/bahlo/generic-list-go/list.go
  vendor/github.com/buger/jsonparser/.gitignore
  vendor/github.com/buger/jsonparser/Dockerfile
  vendor/github.com/buger/jsonparser/LICENSE
  vendor/github.com/buger/jsonparser/Makefile
  vendor/github.com/buger/jsonparser/README.md
  vendor/github.com/buger/jsonparser/bytes.go
  vendor/github.com/buger/jsonparser/bytes_safe.go
  vendor/github.com/buger/jsonparser/bytes_unsafe.go
  vendor/github.com/buger/jsonparser/escape.go
  vendor/github.com/buger/jsonparser/fuzz.go
  vendor/github.com/buger/jsonparser/oss-fuzz-build.sh
  vendor/github.com/buger/jsonparser/parser.go
  vendor/github.com/karimkhaleel/jsonschema/.gitignore
  vendor/github.com/karimkhaleel/jsonschema/.golangci.yml
  vendor/github.com/karimkhaleel/jsonschema/COPYING
  vendor/github.com/karimkhaleel/jsonschema/README.md
  vendor/github.com/karimkhaleel/jsonschema/comment_extractor.go
  vendor/github.com/karimkhaleel/jsonschema/id.go
  vendor/github.com/karimkhaleel/jsonschema/reflect.go
  vendor/github.com/karimkhaleel/jsonschema/utils.go
  vendor/github.com/mailru/easyjson/LICENSE
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/github.com/wk8/go-ordered-map/v2/.gitignore
  vendor/github.com/wk8/go-ordered-map/v2/.golangci.yml
  vendor/github.com/wk8/go-ordered-map/v2/CHANGELOG.md
  vendor/github.com/wk8/go-ordered-map/v2/LICENSE
  vendor/github.com/wk8/go-ordered-map/v2/Makefile
  vendor/github.com/wk8/go-ordered-map/v2/README.md
  vendor/github.com/wk8/go-ordered-map/v2/json.go
  vendor/github.com/wk8/go-ordered-map/v2/orderedmap.go
  vendor/github.com/wk8/go-ordered-map/v2/yaml.go
  vendor/modules.txt
Labels: enhancement, blocks-release

#3086 Re-enable 'Unset upstream' option when upstream branch is missing
  pkg/gui/controllers/branches_controller.go
  pkg/integration/tests/branch/reset_upstream.go
  pkg/integration/tests/branch/unset_upstream.go
  pkg/integration/tests/test_list.go
Labels: bug, requires-maintainer-signoff

#3104 Add a copy-to-clipboard menu to the file view (with `diff` copy options)
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/diff.go
  pkg/config/user_config.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/filetree/file_node.go
  pkg/gui/filetree/node.go
  pkg/i18n/english.go
  pkg/integration/tests/file/copy_menu.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3148 fix: MacOS default path misspelling
  docs/Config.md
Labels: docs

#3076 Fix bottom line alignment
  pkg/gui/context/context.go
  pkg/gui/context/setup.go
  pkg/gui/controllers/helpers/window_arrangement_helper.go
  pkg/gui/controllers/helpers/window_arrangement_helper_test.go
  pkg/gui/types/views.go
  pkg/gui/views.go
Labels: enhancement

#3083 Fall back to WithWaitingStatus if item is not visible
  pkg/gui/context/list_context_trait.go
  pkg/gui/context/list_view_model.go
  pkg/gui/controllers.go
  pkg/gui/controllers/helpers/inline_status_helper.go
  pkg/gui/controllers/helpers/window_helper.go
  pkg/gui/filetree/commit_file_tree.go
  pkg/gui/filetree/file_tree.go
  pkg/gui/main_panels.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/item_operations.go
  pkg/gui/presentation/tags.go
  pkg/gui/types/context.go
Labels: bug, blocks-release

#3163 fix(config): add `yaml:"options"` struct tag to `CustomCommandPrompt`.`[]Options`
  pkg/config/user_config.go
  schema/config.json
Labels: maintenance

#3171 Add remote branch sorting menu, saving the option to state.yml
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/remote_loader.go
  pkg/config/app_config.go
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/i18n/english.go
  pkg/i18n/japanese.go
  pkg/i18n/russian.go
  pkg/integration/components/shell.go
  pkg/integration/tests/branch/sort_remote_branches.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3174 Add age to stash entries
  pkg/commands/git_commands/stash_loader.go
  pkg/commands/git_commands/stash_loader_test.go
  pkg/commands/models/stash_entry.go
  pkg/gui/presentation/stash_entries.go
  pkg/integration/tests/stash/rename.go
  pkg/integration/tests/stash/stash.go
Labels: enhancement

#3182 Add local branch sorting menu
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/branch_loader.go
  pkg/commands/git_commands/branch_loader_test.go
  pkg/config/app_config.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/sort_local_branches.go
  pkg/integration/tests/test_list.go
Labels: enhancement
