Repository jesseduffield/lazygit, pull requests merged in 2023-10, with the labels that each got.

#3037 Add ability to force portrait mode
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/window_arrangement_helper.go
Labels: enhancement

#3047 Band-aid fix for submodule/reset.go test failure
  pkg/gui/controllers/helpers/refresh_helper.go
Labels: maintenance

#3049 Add Micro editor preset
  docs/Config.md
  pkg/config/editor_presets.go
Labels: enhancement

#3051 Remove redundant `len` check
  pkg/commands/hosting_service/hosting_service.go
Labels: maintenance

#3060 Add disabled compat for user config (#2833)
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/keybindings/keybindings.go
  pkg/integration/tests/misc/disabled_keybindings.go
  pkg/integration/tests/test_list.go
Labels: maintenance

#3021 Show sync status in branches list
  pkg/commands/git.go
  pkg/commands/git_commands/common.go
  pkg/commands/git_commands/remote.go
  pkg/commands/git_commands/sync.go
  pkg/commands/git_commands/tag.go
  pkg/commands/models/branch.go
  pkg/commands/models/tag.go
  pkg/gui/context/branches_context.go
  pkg/gui/context/tags_context.go
  pkg/gui/controllers.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/helpers.go
  pkg/gui/controllers/helpers/inline_status_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/repos_helper.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/controllers/sync_controller.go
  pkg/gui/controllers/tags_controller.go
  pkg/gui/gui.go
  pkg/gui/gui_common.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/item_operations.go
  pkg/gui/presentation/status.go
  pkg/gui/presentation/tags.go
  pkg/gui/types/common.go
  pkg/i18n/chinese.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/korean.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
Labels: enhancement

#3058 Re-apply filter when model changes
  pkg/gui/context/filtered_list.go
  pkg/gui/controllers.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/search_helper.go
  pkg/gui/types/context.go
  pkg/integration/tests/filter_and_search/filter_updates_when_model_changes.go
  pkg/integration/tests/test_list.go
Labels: bug

#3074 Add 'lvim' editor preset for lunarvim
  docs/Config.md
  pkg/config/editor_presets.go
Labels: enhancement
