Repository jesseduffield/lazygit, pull requests merged in 2023-07, with the labels that each got.

#2797 Update release notes config and add CI check
  .github/release.yml
  .github/workflows/ci.yml
Labels: maintenance

#2798 Add missing label to label checker
  .github/workflows/ci.yml
Labels: ignore-for-release

#2799 Fix crash on empty menu
  pkg/gui/context/menu_context.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/menu_controller.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/ui/empty_menu.go
Labels: bug

#2807 Include more commit authors in author suggestions
  pkg/commands/models/author.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/suggestions_helper.go
  pkg/gui/controllers/switch_to_sub_commits_controller.go
  pkg/gui/gui.go
  pkg/gui/types/common.go
  pkg/integration/tests/commit/set_author.go
Labels: enhancement

#2808 Use fuzzy search when filtering a view
  pkg/gui/context/filtered_list.go
  pkg/integration/components/view_driver.go
  pkg/integration/tests/filter_and_search/filter_fuzzy.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2809 Better tag creation UX
  pkg/cheatsheet/generate.go
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
  pkg/commands/git_commands/patch.go
  pkg/commands/git_commands/rebase.go
  pkg/gui/context/commit_message_context.go
  pkg/gui/controllers.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/helpers/tags_helper.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/tags_controller.go
  pkg/i18n/chinese.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/japanese.go
  pkg/i18n/korean.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/integration/components/commit_description_panel_driver.go
  pkg/integration/tests/branch/create_tag.go
  pkg/integration/tests/commit/create_tag.go
  pkg/integration/tests/tag/create_while_committing.go
  pkg/integration/tests/tag/crud_annotated.go
  pkg/integration/tests/tag/crud_lightweight.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2812 Better word wrap
  go.mod
  go.sum
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: enhancement

#2813 Fix crash caused by simultaneous read/write of scanner buffer
  pkg/tasks/tasks.go
Labels: bug

#2800 Prompt for commit message when moving a custom patch to a new commit
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/patch.go
  pkg/gui/controllers/custom_patch_options_menu_action.go
  pkg/integration/tests/patch_building/move_to_new_commit.go
  pkg/integration/tests/patch_building/move_to_new_commit_partial_hunk.go
Labels: enhancement

#2811 README.md: Add Gentoo installation documentation
  README.md
Labels: docs

#2818 Support typing special characters like '[' on non-english keyboards
  pkg/gui/editors.go
Labels: bug

#2821 Fix infinite wait on push/pull on windows
  pkg/commands/oscommands/cmd_obj_runner.go
Labels: bug

#2832 Fix issue where using `null` to un-map a keybinding was ignored
  go.mod
  go.sum
  pkg/config/app_config.go
  pkg/config/dummies.go
  vendor/github.com/jesseduffield/yaml/LICENSE
  vendor/github.com/jesseduffield/yaml/LICENSE.libyaml
  vendor/github.com/jesseduffield/yaml/NOTICE
  vendor/github.com/jesseduffield/yaml/README.md
  vendor/github.com/jesseduffield/yaml/apic.go
  vendor/github.com/jesseduffield/yaml/decode.go
  vendor/github.com/jesseduffield/yaml/emitterc.go
  vendor/github.com/jesseduffield/yaml/encode.go
  vendor/github.com/jesseduffield/yaml/parserc.go
  vendor/github.com/jesseduffield/yaml/readerc.go
  vendor/github.com/jesseduffield/yaml/resolve.go
  vendor/github.com/jesseduffield/yaml/scannerc.go
  vendor/github.com/jesseduffield/yaml/sorter.go
  vendor/github.com/jesseduffield/yaml/writerc.go
  vendor/github.com/jesseduffield/yaml/yaml.go
  vendor/github.com/jesseduffield/yaml/yamlh.go
  vendor/github.com/jesseduffield/yaml/yamlprivateh.go
  vendor/modules.txt
Labels: bug

#2829 Show error when trying to open patch menu with an empty patch
  pkg/gui/controllers/custom_patch_options_menu_action.go
  pkg/i18n/english.go
Labels: bug

#2841 Faster refresh
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/git_commands/deps_test.go
  pkg/commands/git_commands/patch_test.go
  pkg/commands/git_commands/rebase_test.go
  pkg/commands/git_commands/reflog_commit_loader.go
  pkg/commands/git_commands/remote_loader.go
  pkg/commands/oscommands/cmd_obj_runner.go
  pkg/commands/oscommands/fake_cmd_obj_runner.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/view_helpers.go
Labels: enhancement

#2784 feat: add os.copyToClipboardCmd to allow for a custom command #1055
  docs/Config.md
  pkg/commands/oscommands/os.go
  pkg/config/user_config.go
  pkg/integration/tests/misc/copy_to_clipboard.go
  pkg/integration/tests/patch_building/copy_patch_to_clipboard.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2844 Fix the x/exp dependency
  go.mod
Labels: ignore-for-release

#2838 Add bisect menu entry that lets you choose bisect terms
  pkg/commands/git_commands/bisect.go
  pkg/gui/controllers/bisect_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/bisect/choose_terms.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2837 When bisecting, always mark the current commit as good/bad, not the selected
  pkg/gui/controllers/bisect_controller.go
  pkg/i18n/chinese.go
  pkg/i18n/english.go
  pkg/i18n/japanese.go
  pkg/i18n/korean.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/integration/tests/bisect/skip.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2846 Standardise on using lo for slice functions
  pkg/app/app.go
  pkg/app/daemon/rebase.go
  pkg/app/errors.go
  pkg/cheatsheet/generate.go
  pkg/commands/git_commands/bisect_info.go
  pkg/commands/git_commands/branch_loader.go
  pkg/commands/git_commands/commit_file_loader.go
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/rebase.go
  pkg/commands/git_commands/remote_loader.go
  pkg/commands/git_commands/stash_loader.go
  pkg/commands/git_commands/tag_loader.go
  pkg/commands/hosting_service/hosting_service.go
  pkg/commands/oscommands/os.go
  pkg/commands/patch/patch_builder.go
  pkg/gui/context.go
  pkg/gui/context/commit_files_context.go
  pkg/gui/context/menu_context.go
  pkg/gui/context/working_tree_context.go
  pkg/gui/controllers/custom_command_action.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/helpers/mode_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/helpers/repos_helper.go
  pkg/gui/controllers/helpers/suggestions_helper.go
  pkg/gui/controllers/helpers/upstream_helper_test.go
  pkg/gui/controllers/options_menu_action.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/filetree/commit_file_tree.go
  pkg/gui/filetree/file_tree.go
  pkg/gui/filetree/node.go
  pkg/gui/layout.go
  pkg/gui/modes/cherrypicking/cherry_picking.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/graph/graph.go
  pkg/gui/presentation/reflog_commits.go
  pkg/gui/presentation/remote_branches.go
  pkg/gui/presentation/remotes.go
  pkg/gui/presentation/stash_entries.go
  pkg/gui/presentation/submodules.go
  pkg/gui/presentation/suggestions.go
  pkg/gui/presentation/tags.go
  pkg/gui/services/custom_commands/handler_creator.go
  pkg/gui/services/custom_commands/keybinding_creator.go
  pkg/gui/status/status_manager.go
  pkg/gui/views.go
  pkg/integration/clients/cli.go
  pkg/integration/clients/tui.go
  pkg/integration/components/test.go
  pkg/integration/tests/tests.go
  pkg/utils/formatting.go
  pkg/utils/search.go
  pkg/utils/slice.go
  vendor/github.com/jesseduffield/generics/slices/delegated_slices.go
  vendor/github.com/jesseduffield/generics/slices/delegated_sort.go
  vendor/github.com/jesseduffield/generics/slices/slices.go
  vendor/modules.txt
Labels: maintenance

#2847 Remove redundant secureexec package
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .golangci.yml
  Dockerfile
  go.mod
  go.sum
  pkg/app/daemon/daemon.go
  pkg/app/entry_point.go
  pkg/commands/git_config/get_key.go
  pkg/commands/oscommands/cmd_obj.go
  pkg/commands/oscommands/cmd_obj_builder.go
  pkg/commands/oscommands/cmd_obj_test.go
  pkg/commands/oscommands/fake_cmd_obj_runner.go
  pkg/commands/oscommands/os_windows_test.go
  pkg/integration/clients/tui.go
  pkg/integration/components/shell.go
  pkg/logs/tail/logs_default.go
  pkg/secureexec/secureexec_default.go
  pkg/secureexec/secureexec_windows.go
  pkg/tasks/tasks_test.go
  vendor/github.com/cli/safeexec/LICENSE
  vendor/github.com/cli/safeexec/README.md
  vendor/github.com/cli/safeexec/lookpath.go
  vendor/github.com/cli/safeexec/lookpath_windows.go
  vendor/modules.txt
Labels: maintenance

#2845 Fix merge status for update-ref command
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
Labels: bug

#2775 Visualize local branch heads in commits panel, 2nd approach
  docs/Config.md
  docs/README.md
  docs/Stacked_Branches.md
  pkg/commands/git_commands/branch.go
  pkg/commands/git_commands/branch_loader.go
  pkg/commands/git_commands/config.go
  pkg/commands/git_commands/status.go
  pkg/config/user_config.go
  pkg/gui/context/branches_context.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/reflog_commits_context.go
  pkg/gui/context/remote_branches_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/context/tags_context.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/switch_to_sub_commits_controller.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/commits.go
  pkg/gui/presentation/commits_test.go
  pkg/gui/types/common.go
  pkg/integration/tests/bisect/basic.go
  pkg/integration/tests/interactive_rebase/drop_todo_commit_with_update_ref.go
  pkg/integration/tests/interactive_rebase/drop_todo_commit_with_update_ref_show_branch_heads.go
  pkg/integration/tests/reflog/do_not_show_branch_markers_in_reflog_subcommits.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2835 Rebase onto branch from a marked base commit
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/rebase.go
  pkg/config/user_config.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/helpers/mode_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/gui.go
  pkg/gui/modes/marked_base_commit/marked_base_commit.go
  pkg/gui/presentation/commits.go
  pkg/gui/presentation/commits_test.go
  pkg/gui/types/modes.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/rebase_from_marked_base.go
  pkg/integration/tests/test_list.go
  pkg/theme/theme.go
Labels: feature

#2827 Allow force-tagging if tag exists
  pkg/commands/git_commands/tag.go
  pkg/gui/controllers/helpers/tags_helper.go
  pkg/gui/controllers/sync_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/sync/force_push.go
  pkg/integration/tests/sync/force_push_multiple_matching.go
  pkg/integration/tests/sync/force_push_multiple_upstream.go
  pkg/integration/tests/tag/force_tag_annotated.go
  pkg/integration/tests/tag/force_tag_lightweight.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2830 Save IgnoreWhitespaceInDiffView in state.yml
  pkg/config/app_config.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/diff_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/reflog_commits_controller.go
  pkg/gui/controllers/stash_controller.go
  pkg/gui/controllers/sub_commits_controller.go
  pkg/gui/controllers/submodules_controller.go
  pkg/gui/controllers/toggle_whitespace_action.go
  pkg/gui/extras_panel.go
  pkg/gui/gui.go
  pkg/gui/types/common.go
Labels: enhancement

#2853 Add automated demo recordings
  .gitignore
  demo/README.md
  demo/config.yml
  demo/record_demo.sh
  docs/dev/Demo_Recordings.md
  docs/dev/README.md
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/window_arrangement_helper.go
  pkg/gui/global_handlers.go
  pkg/gui/gui.go
  pkg/gui/gui_common.go
  pkg/gui/gui_driver.go
  pkg/gui/options_map.go
  pkg/gui/popup/popup_handler.go
  pkg/gui/types/common.go
  pkg/integration/clients/go_test.go
  pkg/integration/clients/tui.go
  pkg/integration/components/commit_description_panel_driver.go
  pkg/integration/components/random.go
  pkg/integration/components/shell.go
  pkg/integration/components/test.go
  pkg/integration/components/test_driver.go
  pkg/integration/components/test_test.go
  pkg/integration/components/view_driver.go
  pkg/integration/tests/demo/bisect.go
  pkg/integration/tests/demo/cherry_pick.go
  pkg/integration/tests/demo/commit_and_push.go
  pkg/integration/tests/demo/interactive_rebase.go
  pkg/integration/tests/test_list.go
  pkg/integration/types/types.go
  scripts/record_demo.sh
  test/default_test_config/config.yml
Labels: maintenance

#2851 Show loader when rebasing
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
Labels: enhancement
