Repository jesseduffield/lazygit, pull requests merged in 2023-08, with the labels that each got.

#2852 Internationalise logging of commands
  pkg/commands/git_commands/rebase.go
  pkg/commands/oscommands/os.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/merge_conflicts_controller.go
  pkg/i18n/english.go
Labels: enhancement

#2863 Stop worktrees view from stealing the window
  .golangci.yml
  pkg/commands/oscommands/copy.go
  pkg/config/config_linux.go
  pkg/gui/controllers/workspace_reset_controller.go
  pkg/gui/views.go
  pkg/integration/clients/go_test.go
  pkg/integration/components/runner.go
  pkg/integration/tests/test_list_generator.go
Labels: bug

#2854 Auto-refresh on window activation
  go.mod
  go.sum
  pkg/gui/gui.go
  vendor/github.com/gdamore/tcell/v2/README.md
  vendor/github.com/gdamore/tcell/v2/console_win.go
  vendor/github.com/gdamore/tcell/v2/focus.go
  vendor/github.com/gdamore/tcell/v2/screen.go
  vendor/github.com/gdamore/tcell/v2/simulation.go
  vendor/github.com/gdamore/tcell/v2/terminfo/terminfo.go
  vendor/github.com/gdamore/tcell/v2/tscreen.go
  vendor/github.com/jesseduffield/gocui/edit.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/github.com/jesseduffield/gocui/tcell_driver.go
  vendor/modules.txt
Labels: feature

#2865 Remove file watcher code
  go.mod
  go.sum
  pkg/gui/controllers.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/file_watching.go
  pkg/gui/gui.go
  pkg/gui/types/common.go
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/modules.txt
Labels: maintenance

#2866 Add more demos to the README
  README.md
  demo/record_demo.sh
  docs/dev/Demo_Recordings.md
  pkg/integration/components/confirmation_driver.go
  pkg/integration/tests/demo/amend_old_commit.go
  pkg/integration/tests/demo/filter.go
  pkg/integration/tests/demo/stage_lines.go
  pkg/integration/tests/test_list.go
Labels: maintenance

#2867 Move features to top of readme
  README.md
Labels: maintenance

#2874 Add more demos
  README.md
  pkg/integration/components/menu_driver.go
  pkg/integration/tests/demo/custom_command.go
  pkg/integration/tests/demo/custom_patch.go
  pkg/integration/tests/demo/undo.go
  pkg/integration/tests/demo/worktree_create_from_branches.go
  pkg/integration/tests/test_list.go
Labels: maintenance

#2879 Fix confirmation view sizing
  pkg/gui/controllers/helpers/confirmation_helper.go
Labels: bug

#2895 update worktree icons for NerdFont V3
  pkg/gui/presentation/icons/git_icons.go
Labels: bug

#2896 Don't run the check-required-label check on master
  .github/workflows/ci.yml
Labels: maintenance

#2901 Use nerdfont version 3 in demos
  demo/config.yml
  pkg/integration/tests/demo/amend_old_commit.go
  pkg/integration/tests/demo/bisect.go
  pkg/integration/tests/demo/cherry_pick.go
  pkg/integration/tests/demo/commit_and_push.go
  pkg/integration/tests/demo/custom_patch.go
  pkg/integration/tests/demo/filter.go
  pkg/integration/tests/demo/interactive_rebase.go
  pkg/integration/tests/demo/nuke_working_tree.go
  pkg/integration/tests/demo/stage_lines.go
  pkg/integration/tests/demo/undo.go
Labels: maintenance

#2902 Fix opening lazygit in a bare repo with specified worktree
  pkg/app/entry_point.go
  pkg/commands/git_commands/repo_paths.go
  pkg/commands/git_commands/worktree_loader.go
  pkg/env/env.go
  pkg/gui/controllers/helpers/repos_helper.go
  pkg/integration/components/paths.go
  pkg/integration/components/runner.go
  pkg/integration/components/test.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/worktree/dotfile_bare_repo.go
Labels: bug

#2903 Fix seg-fault when opening submodule in nested folder
  pkg/commands/git_commands/repo_paths.go
  pkg/commands/git_commands/repo_paths_test.go
Labels: bug

#2893 Mention JSON schema
  docs/Config.md
Labels: docs

#2898 Add Click() to GuiDriver
  cmd/integration_test/main.go
  go.mod
  go.sum
  pkg/gui/gui_driver.go
  pkg/integration/README.md
  pkg/integration/clients/cli.go
  pkg/integration/clients/tui.go
  pkg/integration/components/runner.go
  pkg/integration/components/test.go
  pkg/integration/components/test_driver.go
  pkg/integration/components/test_test.go
  pkg/integration/components/view_driver.go
  pkg/integration/types/types.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/github.com/jesseduffield/gocui/tcell_driver.go
  vendor/modules.txt
Labels: maintenance

#2909 Fix issue where explosion effect was out-of-view
  pkg/gui/controllers/workspace_reset_controller.go
Labels: bug

#2899 Show dialogue when attempting to open info link fails
  pkg/gui/information_panel.go
  pkg/i18n/english.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/ui/open_link_failure.go
Labels: bug

#2919 Fix jumping to the correct line from the staging view
  pkg/commands/patch/patch.go
  pkg/commands/patch/patch_test.go
Labels: bug

#2916 Support editing files in existing neovim instance
  docs/Config.md
  pkg/commands/git_commands/file.go
  pkg/commands/git_commands/file_test.go
  pkg/config/editor_presets.go
  pkg/config/editor_presets_test.go
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/files_helper.go
Labels: enhancement

#2738 Allow deleting remote tags/branches from local tag/branch views
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/branch.go
  pkg/commands/git_commands/branch_test.go
  pkg/commands/git_commands/remote.go
  pkg/commands/git_commands/tag.go
  pkg/gui/controllers.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/branches_helper.go
  pkg/gui/controllers/helpers/helpers.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/gui/controllers/tags_controller.go
  pkg/i18n/chinese.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/japanese.go
  pkg/i18n/korean.go
  pkg/i18n/polish.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/integration/components/git.go
  pkg/integration/components/menu_driver.go
  pkg/integration/components/shell.go
  pkg/integration/components/views.go
  pkg/integration/tests/branch/delete.go
  pkg/integration/tests/tag/crud_annotated.go
  pkg/integration/tests/tag/crud_lightweight.go
  pkg/integration/tests/worktree/detach_worktree_from_branch.go
  pkg/integration/tests/worktree/remove_worktree_from_branch.go
Labels: feature

#2927 Add more demos
  README.md
  docs/Undoing.md
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/integration/components/random.go
  pkg/integration/components/shell.go
  pkg/integration/tests/branch/rebase_from_marked_base.go
  pkg/integration/tests/demo/commit_graph.go
  pkg/integration/tests/demo/rebase_onto.go
  pkg/integration/tests/demo/undo.go
  pkg/integration/tests/test_list.go
Labels: docs

#2928 Show commit mark before showing extra info
  pkg/gui/presentation/commits.go
Labels: enhancement

#2929 Add compare-commits demo
  README.md
  pkg/integration/tests/demo/amend_old_commit.go
  pkg/integration/tests/demo/bisect.go
  pkg/integration/tests/demo/cherry_pick.go
  pkg/integration/tests/demo/commit_and_push.go
  pkg/integration/tests/demo/commit_graph.go
  pkg/integration/tests/demo/custom_command.go
  pkg/integration/tests/demo/custom_patch.go
  pkg/integration/tests/demo/diff_commits.go
  pkg/integration/tests/demo/filter.go
  pkg/integration/tests/demo/interactive_rebase.go
  pkg/integration/tests/demo/nuke_working_tree.go
  pkg/integration/tests/demo/rebase_onto.go
  pkg/integration/tests/demo/shared.go
  pkg/integration/tests/demo/stage_lines.go
  pkg/integration/tests/demo/undo.go
  pkg/integration/tests/demo/worktree_create_from_branches.go
  pkg/integration/tests/test_list.go
Labels: docs

#2915 Jump to middle of the view when selection leaves the visible area
  docs/Config.md
  go.mod
  go.sum
  pkg/commands/patch/patch.go
  pkg/config/user_config.go
  pkg/gui/context/patch_explorer_context.go
  pkg/gui/controllers/list_controller.go
  pkg/gui/controllers/patch_explorer_controller.go
  pkg/gui/controllers/scroll_off_margin.go
  pkg/gui/controllers/scroll_off_margin_test.go
  pkg/gui/patch_exploring/focus.go
  pkg/gui/patch_exploring/focus_test.go
  pkg/gui/patch_exploring/state.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: enhancement

#2935 Add emacs-keybinds for word navigation
  pkg/gui/editors.go
Labels: enhancement

#2946 Fix sha colors when rebasing
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/switch_to_sub_commits_controller.go
Labels: bug

#2943 Fix the commit graph display after selection jumps in commits view
  pkg/gui/context/list_context_trait.go
Labels: bug

#2937 Add Makefile
  Makefile
Labels: maintenance

#2947 Handle trailing slash in worktree path
  pkg/commands/git_commands/repo_paths.go
  pkg/commands/git_commands/repo_paths_test.go
  pkg/commands/git_commands/worktree_loader_test.go
  pkg/utils/formatting_test.go
  pkg/utils/rebase_todo_test.go
Labels: bug

#2785 Feature add git flow instructions
  README.md
Labels: docs

#2939 Add `gui.scrollOffBehavior` config for scrolling list views by half-pages
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/list_controller.go
  pkg/gui/controllers/patch_explorer_controller.go
  pkg/gui/controllers/scroll_off_margin.go
  pkg/gui/controllers/scroll_off_margin_test.go
Labels: enhancement

#2842 Fix: Update 'zh' to 'zh-CN' in lazygit Language Configuration
  docs/Config.md
Labels: docs

#2881 Switch to editor from commit message panel
  pkg/commands/git_commands/commit.go
  pkg/config/user_config.go
  pkg/gui/context/commit_message_context.go
  pkg/gui/controllers/commit_description_controller.go
  pkg/gui/controllers/commit_message_controller.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/views.go
  pkg/i18n/english.go
  pkg/integration/components/commit_message_panel_driver.go
  pkg/integration/tests/commit/commit_switch_to_editor.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#2950 fix GitHub Actions warnings
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/sponsors.yml
Labels: maintenance

#2954 Select same commit again after pressing "e" to edit a commit
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/integration/tests/interactive_rebase/drop_todo_commit_with_update_ref.go
Labels: enhancement

#2960 Support custom keybindings for confirm discard
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/files_remove_controller.go
Labels: enhancement

#2908 Allow adding a port to webDomain part of services config
  pkg/commands/hosting_service/hosting_service.go
  pkg/commands/hosting_service/hosting_service_test.go
Labels: enhancement

#2967 Add instruction in PR template to start PRs with an imperative
  .github/pull_request_template.md
Labels: maintenance

#2727 Add install instructions for openSUSE
  README.md
Labels: docs

#2889 Add icons for files with .mdx and .svelte file extensions
  pkg/gui/presentation/icons/file_icons.go
Labels: enhancement

#2911 Section headers in keybindings menu
  pkg/gui/context/branches_context.go
  pkg/gui/context/commit_files_context.go
  pkg/gui/context/list_context_trait.go
  pkg/gui/context/list_renderer.go
  pkg/gui/context/list_renderer_test.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/menu_context.go
  pkg/gui/context/reflog_commits_context.go
  pkg/gui/context/remote_branches_context.go
  pkg/gui/context/remotes_context.go
  pkg/gui/context/stash_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/context/submodules_context.go
  pkg/gui/context/suggestions_context.go
  pkg/gui/context/tags_context.go
  pkg/gui/context/working_tree_context.go
  pkg/gui/context/worktrees_context.go
  pkg/gui/controllers/list_controller.go
  pkg/gui/controllers/options_menu_action.go
  pkg/gui/menu_panel.go
  pkg/gui/presentation/commits.go
  pkg/gui/presentation/commits_test.go
  pkg/gui/presentation/menu.go
  pkg/gui/types/common.go
  pkg/gui/types/context.go
  pkg/i18n/english.go
  pkg/integration/components/view_driver.go
  pkg/utils/formatting.go
  pkg/utils/formatting_test.go
Labels: enhancement

#2871 Add command to show divergence from upstream
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/models/branch.go
  pkg/commands/models/commit.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/controllers.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/helpers.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/sub_commits_helper.go
  pkg/gui/controllers/switch_to_sub_commits_controller.go
  pkg/gui/presentation/commits.go
  pkg/i18n/english.go
  pkg/integration/components/text_matcher.go
  pkg/integration/tests/branch/show_divergence_from_upstream.go
  pkg/integration/tests/test_list.go
Labels: feature

#2970 Check for staged files for "Amend commit" and "Create fixup commit"
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/gui/controllers/local_commits_controller.go
Labels: enhancement

#2975 Don't show toasts when running integration tests
  pkg/gui/controllers/helpers/app_status_helper.go
  pkg/gui/gui_common.go
  pkg/gui/types/common.go
Labels: maintenance

#2977 Fix escape not cancelling filter mode, but closing the menu instead
  pkg/gui/controllers/menu_controller.go
  pkg/integration/tests/filter_and_search/filter_menu_cancel_filter_with_escape.go
  pkg/integration/tests/test_list.go
Labels: bug
