Repository jesseduffield/lazygit, pull requests merged in 2024-05, with the labels that each got.

#3550 Fix deadlock reporting
  pkg/gui/gui.go
Labels: maintenance

#3547 Fix clicking in status side panel
  pkg/gui/controllers/status_controller.go
  pkg/integration/tests/status/click_repo_name_to_open_repos_menu.go
  pkg/integration/tests/status/click_to_focus.go
  pkg/integration/tests/status/click_working_tree_state_to_open_rebase_options_menu.go
  pkg/integration/tests/test_list.go
Labels: bug

#3569 Fix Stashing partial files for git version >= 2.35.0
  pkg/commands/git_commands/stash.go
  pkg/integration/tests/stash/stash_staged_partial_file.go
  pkg/integration/tests/test_list.go
Labels: bug

#3571 Only run code coverage report on non-fork branches
  .github/workflows/ci.yml
Labels: maintenance

#3572 Attempt #2 at preventing codacy coverage step from running on forks
  .github/workflows/ci.yml
Labels: maintenance

#3508 Improve `nvim-remote` mode
  pkg/config/editor_presets.go
Labels: enhancement

#3534 Delete and edit custom commands history items
  pkg/gui/context/suggestions_context.go
  pkg/gui/controllers/confirmation_controller.go
  pkg/gui/controllers/custom_command_action.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/suggestions_controller.go
  pkg/gui/popup/popup_handler.go
  pkg/gui/types/common.go
  pkg/i18n/english.go
  pkg/integration/components/prompt_driver.go
  pkg/integration/tests/custom_commands/delete_from_history.go
  pkg/integration/tests/custom_commands/edit_history.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3574 Bump go version to 1.22
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .golangci.yml
  Dockerfile
  go.mod
  pkg/commands/git_commands/branch_test.go
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/git_commands/commit_test.go
  pkg/commands/git_commands/file_loader_test.go
  pkg/commands/git_commands/flow_test.go
  pkg/commands/git_commands/rebase_test.go
  pkg/commands/git_commands/reflog_commit_loader_test.go
  pkg/commands/git_commands/repo_paths_test.go
  pkg/commands/git_commands/stash_loader_test.go
  pkg/commands/git_commands/stash_test.go
  pkg/commands/git_commands/sync_test.go
  pkg/commands/git_commands/tag_loader_test.go
  pkg/commands/git_commands/working_tree_test.go
  pkg/commands/git_commands/worktree_loader.go
  pkg/commands/git_commands/worktree_loader_test.go
  pkg/commands/git_config/cached_git_config_test.go
  pkg/commands/hosting_service/hosting_service_test.go
  pkg/commands/oscommands/os.go
  pkg/commands/patch/patch_test.go
  pkg/gui/context/menu_context.go
  pkg/gui/controllers/diffing_menu_action.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/filetree/build_tree_test.go
  pkg/gui/filetree/file_node_test.go
  pkg/gui/filetree/file_tree_test.go
  pkg/gui/mergeconflicts/state_test.go
  pkg/gui/patch_exploring/focus_test.go
  pkg/gui/presentation/commits_test.go
  pkg/gui/presentation/files_test.go
  pkg/gui/presentation/graph/graph.go
  pkg/gui/presentation/graph/graph_test.go
  pkg/gui/services/custom_commands/menu_generator_test.go
  pkg/gui/services/custom_commands/resolver.go
  pkg/gui/style/style_test.go
  pkg/integration/components/runner.go
  pkg/utils/slice_test.go
  pkg/utils/yaml_utils/yaml_utils_test.go
Labels: maintenance

#3528 Correctly request force-pushing in a triangular workflow
  docs/Custom_Command_Keybindings.md
  pkg/commands/git.go
  pkg/commands/git_commands/branch_loader.go
  pkg/commands/git_commands/branch_loader_test.go
  pkg/commands/models/branch.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/sync_controller.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/branches_test.go
  pkg/gui/services/custom_commands/models.go
  pkg/gui/services/custom_commands/session_state_loader.go
  pkg/integration/components/shell.go
  pkg/integration/tests/branch/delete.go
  pkg/integration/tests/branch/delete_remote_branch_with_credential_prompt.go
  pkg/integration/tests/branch/rebase_to_upstream.go
  pkg/integration/tests/branch/reset_to_upstream.go
  pkg/integration/tests/sync/force_push_triangular.go
  pkg/integration/tests/test_list.go
Labels: bug

#3565 Add default lazygit config generation in Config.md from JSON schema
  docs/Config.md
  go.mod
  go.sum
  pkg/config/user_config.go
  pkg/jsonschema/generate_config_docs.go
  pkg/jsonschema/generator.go
  schema/config.json
  vendor/github.com/iancoleman/orderedmap/LICENSE
  vendor/github.com/iancoleman/orderedmap/orderedmap.go
  vendor/github.com/iancoleman/orderedmap/readme.md
  vendor/modules.txt
Labels: maintenance

#3578 Remove hint about Config.md from PR template
  .github/pull_request_template.md
Labels: maintenance

#3586 Add `copyloopvar` to enabled linters
  .golangci.yml
Labels: maintenance

#3593 Add `lint` to make target
  Makefile
Labels: maintenance

#3596 Delete the TODO comment about enabling `goconst` in the future from `.golangci.yml`
  .golangci.yml
Labels: maintenance

#3601 Fix tooltip for fixup command
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/i18n/english.go
Labels: bug

#3611 Pin golangci version to 1.58
  .github/workflows/ci.yml
Labels: maintenance

#3609 Improve branch and reflog loading when sorting branches by date
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/gui.go
Labels: maintenance
