Repository jesseduffield/lazygit, pull requests merged in 2024-03, with the labels that each got.

#3351 Fix linter warnings
  pkg/gui/controllers/helpers/patch_building_helper.go
  pkg/gui/presentation/commits.go
Labels: maintenance

#3349 Make ctrl-f available in staging view
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/gui/controllers/staging_controller.go
Labels: ignore-for-release

#3346 Provide two helix presets, one for "helix" and one for "hx"
  pkg/config/editor_presets.go
Labels: enhancement

#3340 Don't show branch head on rebase todos if the rebase.updateRefs config is on
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/presentation/commits.go
  pkg/integration/tests/interactive_rebase/dont_show_branch_heads_for_todo_items.go
  pkg/integration/tests/interactive_rebase/drop_todo_commit_with_update_ref.go
  pkg/integration/tests/interactive_rebase/quick_start_keep_selection.go
  pkg/integration/tests/interactive_rebase/quick_start_keep_selection_range.go
  pkg/integration/tests/interactive_rebase/view_files_of_todo_entries.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3336 Allow more than one argument in git.merging.args config
  pkg/commands/git_commands/branch.go
  pkg/commands/git_commands/branch_test.go
Labels: bug

#3348 Remove support for old style non-interactive rebase
  pkg/commands/git_commands/commit_loader.go
Labels: maintenance

#3356 Bump gocui
  go.mod
  go.sum
  vendor/github.com/gdamore/tcell/v2/console_win.go
  vendor/github.com/gdamore/tcell/v2/terminfo/a/aixterm/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/a/alacritty/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/c/cygwin/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/e/emacs/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/h/hpterm/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/k/konsole/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/k/kterm/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/l/linux/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/p/pcansi/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/r/rxvt/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/s/screen/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/s/simpleterm/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/t/tmux/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/v/vt100/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/v/vt102/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/v/vt220/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/v/vt320/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/v/vt400/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/v/vt52/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/w/wy50/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/w/wy99_ansi/term.go
  vendor/github.com/gdamore/tcell/v2/terminfo/x/xterm/term.go
  vendor/github.com/gdamore/tcell/v2/tscreen.go
  vendor/modules.txt
Labels: ignore-for-release

#3365 Don't strike out reserved keys in menus
  pkg/gui/context/menu_context.go
Labels: bug

#3341 Show all submodules recursively
  pkg/commands/git_commands/git_command_builder.go
  pkg/commands/git_commands/submodule.go
  pkg/commands/git_commands/working_tree.go
  pkg/commands/models/submodule_config.go
  pkg/gui/context/submodules_context.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/repos_helper.go
  pkg/gui/controllers/submodules_controller.go
  pkg/gui/presentation/submodules.go
  pkg/integration/components/git.go
  pkg/integration/components/shell.go
  pkg/integration/tests/submodule/enter.go
  pkg/integration/tests/submodule/enter_nested.go
  pkg/integration/tests/submodule/remove.go
  pkg/integration/tests/submodule/remove_nested.go
  pkg/integration/tests/submodule/reset.go
  pkg/integration/tests/submodule/shared.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3370 Support setting a range of commits to "edit" outside of a rebase
  pkg/gui/controllers/local_commits_controller.go
  pkg/integration/tests/interactive_rebase/edit_range_select_outside_rebase.go
  pkg/integration/tests/interactive_rebase/mid_rebase_range_select.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3338 Adjust selection after squashing fixups
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/local_commits_controller_test.go
  pkg/i18n/english.go
  pkg/integration/tests/interactive_rebase/squash_fixups_above.go
  pkg/integration/tests/interactive_rebase/squash_fixups_in_current_branch.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3173 Auto-wrap commit message while typing
  docs/Config.md
  go.mod
  go.sum
  pkg/commands/git_commands/commit.go
  pkg/config/user_config.go
  pkg/gui/controllers.go
  pkg/gui/controllers/commit_message_controller.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/helpers/commits_helper_test.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/views.go
  pkg/integration/components/commit_description_panel_driver.go
  pkg/integration/tests/commit/auto_wrap_message.go
  pkg/integration/tests/test_list.go
  schema/config.json
  vendor/github.com/gdamore/tcell/v2/console_win.go
  vendor/github.com/jesseduffield/gocui/text_area.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: enhancement

#3097 Add Co-Author support to new commits
  docs/Config.md
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
  pkg/config/user_config.go
  pkg/gui/context/commit_message_context.go
  pkg/gui/controllers/commit_description_controller.go
  pkg/gui/controllers/commit_message_controller.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/i18n/english.go
  pkg/integration/components/commit_description_panel_driver.go
  pkg/integration/components/commit_message_panel_driver.go
  pkg/integration/tests/commit/add_co_author.go
  pkg/integration/tests/commit/add_co_author_while_committing.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3377 Show "breaking changes" message at startup
  pkg/config/app_config.go
  pkg/gui/gui.go
  pkg/gui/keybindings.go
  pkg/gui/layout.go
  pkg/gui/types/version_number.go
  pkg/gui/types/version_number_test.go
  pkg/i18n/english.go
Labels: enhancement

#3391 Allow moving and deleting update-ref todos
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/rebase.go
  pkg/gui/context/traits/list_cursor.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/presentation/commits.go
  pkg/i18n/english.go
  pkg/integration/tests/interactive_rebase/delete_update_ref_todo.go
  pkg/integration/tests/interactive_rebase/move_update_ref_todo.go
  pkg/integration/tests/test_list.go
  pkg/utils/rebase_todo.go
  pkg/utils/rebase_todo_test.go
Labels: enhancement

#3387 Don't ask to force-push if the remote rejected updates
  pkg/gui/controllers/sync_controller.go
  pkg/i18n/chinese.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/korean.go
  pkg/i18n/polish.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
Labels: bug

#3388 When checking out a remote branch by name, ask the user how
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/branch.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/gui/presentation/item_operations.go
  pkg/gui/types/common.go
  pkg/i18n/english.go
Labels: enhancement

#3376 Use substring filtering instead of fuzzy filtering by default
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/context/branches_context.go
  pkg/gui/context/filtered_list.go
  pkg/gui/context/filtered_list_view_model.go
  pkg/gui/context/menu_context.go
  pkg/gui/context/reflog_commits_context.go
  pkg/gui/context/remote_branches_context.go
  pkg/gui/context/remotes_context.go
  pkg/gui/context/stash_context.go
  pkg/gui/context/submodules_context.go
  pkg/gui/context/tags_context.go
  pkg/gui/context/worktrees_context.go
  pkg/gui/controllers/custom_command_action.go
  pkg/gui/controllers/helpers/search_helper.go
  pkg/gui/controllers/helpers/suggestions_helper.go
  pkg/gui/types/context.go
  pkg/i18n/english.go
  pkg/integration/tests/filter_and_search/filter_fuzzy.go
  pkg/utils/search.go
  pkg/utils/search_test.go
  schema/config.json
Labels: enhancement

#3389 Update translations for polish language
  docs/keybindings/Keybindings_pl.md
  pkg/i18n/polish.go
Labels: i18n

#3395 Fix enabling/disabling of ctrl-o in commit message panel
  pkg/gui/context/commit_message_context.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/i18n/english.go
  pkg/i18n/polish.go
Labels: ignore-for-release

#3393 Fixed translations for zh_TW
  docs/keybindings/Keybindings_zh-TW.md
  pkg/i18n/traditional_chinese.go
Labels: i18n

#3249 Add NixOs installation instructions to README.md
  README.md
Labels: docs

#3410 Always prompt to return from subprocess if there was an error
  pkg/gui/gui.go
Labels: enhancement

#3397 Make the links in the status panel point to the current version rather than master
  pkg/constants/links.go
  pkg/gui/controllers/status_controller.go
Labels: docs

#3401 When adding a new remote, select it and fetch it
  pkg/gui/controllers/remotes_controller.go
Labels: enhancement

#3407 Support editing multiple files at once using range selection
  pkg/commands/git_commands/file.go
  pkg/commands/git_commands/file_test.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/files_helper.go
  pkg/gui/controllers/status_controller.go
  pkg/i18n/english.go
Labels: enhancement

#3402 Add config to truncate commit hashes when copying them to the clipboard
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/global_handlers.go
  pkg/gui/keybindings.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/japanese.go
  pkg/i18n/korean.go
  pkg/i18n/polish.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/integration/tests/misc/copy_to_clipboard.go
  schema/config.json
Labels: enhancement

#3412 Fix container detection
  pkg/config/config_linux.go
Labels: bug

#3392 Update interactive rebase demo
  README.md
  pkg/gui/controllers/helpers/inline_status_helper.go
  pkg/integration/components/view_driver.go
  pkg/integration/tests/demo/interactive_rebase.go
Labels: docs

#3420 Set the `TERM` env variable
  pkg/gui/pty.go
Labels: bug

#3439 Fix deleting update ref todos
  pkg/app/daemon/daemon.go
  pkg/commands/git_commands/rebase.go
  pkg/integration/tests/interactive_rebase/delete_update_ref_todo.go
  pkg/utils/rebase_todo.go
Labels: bug

#3433 Update Busy.md
  docs/dev/Busy.md
Labels: docs

#3450 Fix crash when filtering the keybindings menu
  pkg/gui/context/menu_context.go
  pkg/integration/tests/filter_and_search/filter_menu_with_no_keybindings.go
  pkg/integration/tests/test_list.go
Labels: bug

#3416 Keep the same commit selected when exiting filtering mode
  pkg/gui/context/local_commits_context.go
  pkg/gui/controllers/filtering_menu_action.go
  pkg/gui/controllers/helpers/mode_helper.go
  pkg/gui/modes/filtering/filtering.go
  pkg/integration/tests/filter_by_path/keep_same_commit_selected_on_exit.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3431 Fix rewording signed commits when the log.showsignature git config is true
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
Labels: bug

#3451 Fix schema link in Config.md
  docs/Config.md
Labels: docs

#3446 Make URLs in confirmation panels clickable, and underline them
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/confirmation_helper_test.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/global_handlers.go
  pkg/gui/gui_common.go
  pkg/gui/keybindings.go
  pkg/gui/presentation/branches_test.go
  pkg/gui/presentation/commits_test.go
  pkg/gui/presentation/files_test.go
  pkg/gui/presentation/graph/graph_test.go
  pkg/gui/style/style_test.go
  pkg/gui/types/common.go
  pkg/gui/view_helpers.go
Labels: enhancement
