Repository jesseduffield/lazygit, pull requests merged in 2024-11, with the labels that each got.

#4031 Fix installation for Ubuntu in README.md
  README.md
Labels: docs

#3927 Add config option to disable switching tabs with panel jump keys
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/jump_to_side_window_controller.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/ui/disable_switch_tab_with_panel_jump_keys.go
  pkg/integration/tests/ui/switch_tab_with_panel_jump_keys.go
  schema/config.json
Labels: enhancement

#3970 Fixes to lazygit Ubuntu install instructions in README.md
  README.md
Labels: docs

#4024 Add new filter to only show tracked files in Files panel
  pkg/gui/controllers/files_controller.go
  pkg/gui/filetree/file_tree.go
  pkg/gui/filetree/file_tree_test.go
  pkg/i18n/english.go
Labels: enhancement

#4063 ci: update `upload-artifact` and `download-artifact` actions to v4
  .github/workflows/ci.yml
Labels: maintenance

#1889 Allow user to select remote and branch when creating a PR
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/suggestions_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/open_pull_request_invalid_target_remote_name.go
  pkg/integration/tests/branch/open_pull_request_select_remote_and_target_branch.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4092 Let schema/config.json end with a line feed
  pkg/jsonschema/generate.go
  schema/config.json
Labels: maintenance
