Repository jesseduffield/lazygit, pull requests merged in 2024-12, with the labels that each got.

#4084 Cleanup background fetch
  pkg/gui/background.go
  pkg/gui/gui.go
  pkg/gui/recent_repos_panel.go
  pkg/i18n/english.go
Labels: maintenance

#4073 Delete range selection of branches
  pkg/commands/git_commands/branch.go
  pkg/commands/git_commands/branch_test.go
  pkg/commands/git_commands/remote.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/branches_helper.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/delete.go
  pkg/integration/tests/branch/delete_multiple.go
  pkg/integration/tests/branch/shared.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4097 commits panel: add missing default sort order
  pkg/gui/controllers/local_commits_controller.go
Labels: bug

#3850 Fix issues with opening links and files using WSL
  pkg/config/config_linux.go
Labels: bug

#4120 remove duplicate secondary MouseWheelUp keybind
  pkg/gui/keybindings.go
Labels: maintenance

#4121 Fix typos
  docs/Config.md
  pkg/config/user_config.go
  schema/config.json
Labels: docs

#4094 Drop merge commits
  pkg/app/daemon/daemon.go
  pkg/commands/git_commands/rebase.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/interactive_rebase/drop_merge_commit.go
  pkg/integration/tests/test_list.go
  pkg/utils/rebase_todo.go
  pkg/utils/rebase_todo_test.go
Labels: enhancement

#4096 Fix moving a commit across a branch boundary in a stack of branches
  pkg/app/daemon/daemon.go
  pkg/commands/git_commands/rebase.go
  pkg/integration/tests/interactive_rebase/move_across_branch_boundary_outside_rebase.go
  pkg/integration/tests/test_list.go
  pkg/utils/rebase_todo.go
  pkg/utils/rebase_todo_test.go
Labels: bug

#4098 Wrap lines in staging view
  docs/Config.md
  go.mod
  go.sum
  pkg/config/user_config.go
  pkg/gui/context/patch_explorer_context.go
  pkg/gui/context/simple_context.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/patch_building_helper.go
  pkg/gui/controllers/helpers/staging_helper.go
  pkg/gui/controllers/patch_building_controller.go
  pkg/gui/controllers/patch_explorer_controller.go
  pkg/gui/controllers/staging_controller.go
  pkg/gui/patch_exploring/state.go
  pkg/utils/lines.go
  pkg/utils/lines_test.go
  schema/config.json
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: enhancement

#4110 Don't preserve commit message when it's unchanged from initial message
  pkg/gui/context/commit_message_context.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/integration/tests/commit/commit_with_prefix.go
Labels: bug

#4126 Fix hang when returning from shell command
  pkg/commands/oscommands/cmd_obj_builder.go
  pkg/commands/oscommands/dummies.go
  pkg/commands/oscommands/os.go
  pkg/commands/oscommands/os_default_platform.go
  pkg/commands/oscommands/os_windows.go
Labels: bug

#4053 Add vision and design principles doc
  CONTRIBUTING.md
  VISION.md
Labels: docs
