Repository jesseduffield/lazygit, pull requests merged in 2024-01, with the labels that each got.

#3179 Fix checking out a tag when there is a branch with the same name
  pkg/gui/controllers/tags_controller.go
  pkg/integration/tests/tag/checkout_when_branch_with_same_name_exists.go
  pkg/integration/tests/test_list.go
Labels: bug

#3156 Add command to open git difftool
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/diff.go
  pkg/commands/git_commands/working_tree.go
  pkg/config/user_config.go
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/i18n/english.go
  schema/config.json
Labels: feature

#3170 Fix preserving the commit message when description contains blank lines
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/integration/components/commit_description_panel_driver.go
  pkg/integration/components/commit_message_panel_driver.go
  pkg/integration/tests/commit/preserve_commit_message.go
  pkg/integration/tests/test_list.go
Labels: bug

#3133 Add config setting for splitting window vertically in half screen mode
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/window_arrangement_helper.go
  pkg/gui/controllers/helpers/window_arrangement_helper_test.go
  schema/config.json
Labels: enhancement

#3105 Add command to find base commit for creating a fixup
  docs/Config.md
  docs/Fixup_Commits.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git.go
  pkg/commands/git_commands/blame.go
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/diff.go
  pkg/config/user_config.go
  pkg/gui/controllers.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/fixup_helper.go
  pkg/gui/controllers/helpers/helpers.go
  pkg/i18n/english.go
  pkg/integration/tests/commit/find_base_commit_for_fixup.go
  pkg/integration/tests/commit/find_base_commit_for_fixup_warning_for_added_lines.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3202 Allow multiple fetch commands (or fetch and pull) to run concurrently
  pkg/commands/git_commands/rebase.go
  pkg/commands/git_commands/sync.go
  pkg/commands/git_commands/version.go
  pkg/commands/git_commands/version_test.go
  pkg/integration/components/test.go
Labels: bug

#3206 Add codebase guide
  CONTRIBUTING.md
  docs/dev/Codebase_Guide.md
  docs/dev/README.md
Labels: docs

#3215 Set working directory in lazygit test command
  pkg/integration/README.md
  pkg/integration/clients/cli.go
  pkg/integration/clients/go_test.go
  pkg/integration/clients/injector/main.go
  pkg/integration/clients/tui.go
  pkg/integration/components/runner.go
  pkg/integration/components/test.go
  pkg/integration/tests/filter_by_path/cli_arg.go
  pkg/integration/tests/tests.go
  pkg/integration/tests/worktree/bare_repo.go
  pkg/integration/tests/worktree/dotfile_bare_repo.go
Labels: maintenance

#3213 Add 'Quick start interactive rebase' action
  README.md
  docs/dev/Codebase_Guide.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/config/user_config.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/i18n/english.go
  pkg/integration/components/common.go
  pkg/integration/tests/interactive_rebase/quick_start.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: feature

#3180 Show Toast instead of error panel when invoking a disabled command
  pkg/app/app.go
  pkg/cheatsheet/generate.go
  pkg/gui/context/menu_context.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/app_status_helper.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/options_menu_action.go
  pkg/gui/controllers/sync_controller.go
  pkg/gui/dummies.go
  pkg/gui/gui.go
  pkg/gui/gui_driver.go
  pkg/gui/keybindings.go
  pkg/gui/popup/popup_handler.go
  pkg/gui/status/status_manager.go
  pkg/gui/test_mode.go
  pkg/gui/types/common.go
  pkg/gui/types/keybindings.go
  pkg/integration/components/menu_driver.go
  pkg/integration/components/test.go
  pkg/integration/components/test_driver.go
  pkg/integration/components/test_test.go
  pkg/integration/tests/branch/delete.go
  pkg/integration/tests/branch/rebase_to_upstream.go
  pkg/integration/tests/branch/reset_to_upstream.go
  pkg/integration/tests/file/copy_menu.go
  pkg/integration/tests/interactive_rebase/amend_non_head_commit_during_rebase.go
  pkg/integration/tests/interactive_rebase/edit_non_todo_commit_during_rebase.go
  pkg/integration/tests/interactive_rebase/edit_the_confl_commit.go
  pkg/integration/tests/interactive_rebase/fixup_first_commit.go
  pkg/integration/tests/interactive_rebase/quick_start.go
  pkg/integration/tests/interactive_rebase/squash_down_first_commit.go
  pkg/integration/tests/misc/copy_to_clipboard.go
  pkg/integration/tests/staging/diff_context_change.go
  pkg/integration/tests/tag/crud_annotated.go
  pkg/integration/tests/tag/crud_lightweight.go
  pkg/integration/types/types.go
Labels: enhancement

#3220 Do not include keybindings from another view in keybindings menu
  pkg/gui/controllers/options_menu_action.go
Labels: bug

#3219 Fix crash with short branch names
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/branches_test.go
Labels: bug

#3221 Fix CI erroneously marking failed tests as successful
  scripts/run_integration_tests.sh
Labels: maintenance

#3186 Keep same branch selected when fetching a branch while sorted by date
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/types/refresh.go
  pkg/integration/tests/custom_commands/suggestions_command.go
  pkg/integration/tests/custom_commands/suggestions_preset.go
  pkg/integration/tests/sync/fetch_when_sorted_by_date.go
  pkg/integration/tests/test_list.go
Labels: bug

#3081 Show file names in default colour
  pkg/gui/context/commit_files_context.go
  pkg/gui/context/working_tree_context.go
  pkg/gui/presentation/files.go
  pkg/gui/presentation/files_test.go
Labels: enhancement

#3234 Make range selections created with the mouse non-sticky
  pkg/gui/controllers/patch_explorer_controller.go
  pkg/gui/patch_exploring/state.go
Labels: enhancement

#3183 Use git rev-parse to obtain repository and worktree paths
  .editorconfig
  pkg/commands/git.go
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
  pkg/commands/git_commands/diff.go
  pkg/commands/git_commands/repo_paths.go
  pkg/commands/git_commands/repo_paths_test.go
  pkg/commands/git_commands/stash.go
  pkg/commands/git_commands/stash_test.go
  pkg/commands/git_commands/working_tree.go
  pkg/commands/git_commands/working_tree_test.go
  pkg/commands/git_commands/worktree_loader.go
  pkg/commands/git_commands/worktree_loader_test.go
  pkg/commands/git_test.go
  pkg/commands/oscommands/cmd_obj_builder.go
  pkg/integration/components/env.go
  pkg/integration/components/runner.go
  pkg/integration/components/shell.go
  pkg/integration/components/test.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/worktree/bare_repo_worktree_config.go
  pkg/integration/tests/worktree/double_nested_linked_submodule.go
  pkg/integration/tests/worktree/symlink_into_repo_subdir.go
  pkg/tasks/tasks.go
  test/.gitconfig
Labels: bug

#3248 Support range select for staging/discarding files
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/working_tree.go
  pkg/gui/controllers.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/files_remove_controller.go
  pkg/gui/filetree/node.go
  pkg/i18n/english.go
  pkg/integration/components/view_driver.go
  pkg/integration/tests/file/discard_all_dir_changes.go
  pkg/integration/tests/file/discard_changes.go
  pkg/integration/tests/file/discard_range_select.go
  pkg/integration/tests/file/discard_unstaged_dir_changes.go
  pkg/integration/tests/file/discard_unstaged_file_changes.go
  pkg/integration/tests/file/discard_unstaged_range_select.go
  pkg/integration/tests/file/discard_various_changes.go
  pkg/integration/tests/file/discard_various_changes_range_select.go
  pkg/integration/tests/file/remember_commit_message_after_fail.go
  pkg/integration/tests/file/shared.go
  pkg/integration/tests/file/stage_range_select.go
  pkg/integration/tests/patch_building/apply_in_reverse_with_conflict.go
  pkg/integration/tests/patch_building/move_to_index_with_conflict.go
  pkg/integration/tests/submodule/reset.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/worktree/worktree_in_repo.go
  pkg/utils/formatting.go
Labels: enhancement

#3255 Pass absolute file paths to all editor commands
  pkg/gui/controllers/helpers/files_helper.go
Labels: bug

#3238 Inline status for fetching remotes
  pkg/commands/models/remote.go
  pkg/gui/context/remotes_context.go
  pkg/gui/controllers/remotes_controller.go
  pkg/gui/presentation/item_operations.go
  pkg/gui/presentation/remotes.go
  pkg/gui/types/common.go
  pkg/i18n/chinese.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/japanese.go
  pkg/i18n/korean.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
Labels: enhancement

#3247 Keep same selection range when quick-starting an interactive rebase
  pkg/gui/context/traits/list_cursor.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/integration/tests/interactive_rebase/quick_start_keep_selection.go
  pkg/integration/tests/interactive_rebase/quick_start_keep_selection_range.go
  pkg/integration/tests/test_list.go
  pkg/utils/utils.go
Labels: enhancement

#3269 Add loads of tooltips
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/cheatsheet/generate.go
  pkg/constants/links.go
  pkg/gui/controllers.go
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/context_lines_controller.go
  pkg/gui/controllers/custom_patch_options_menu_action.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/global_controller.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/merge_conflicts_controller.go
  pkg/gui/controllers/patch_building_controller.go
  pkg/gui/controllers/patch_explorer_controller.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/gui/controllers/remotes_controller.go
  pkg/gui/controllers/staging_controller.go
  pkg/gui/controllers/stash_controller.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/controllers/submodules_controller.go
  pkg/gui/controllers/sync_controller.go
  pkg/gui/controllers/tags_controller.go
  pkg/gui/controllers/worktrees_controller.go
  pkg/gui/keybindings.go
  pkg/gui/types/keybindings.go
  pkg/i18n/chinese.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/japanese.go
  pkg/i18n/korean.go
  pkg/i18n/polish.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/integration/tests/filter_and_search/filter_menu.go
  pkg/integration/tests/filter_and_search/filter_menu_cancel_filter_with_escape.go
  pkg/integration/tests/interactive_rebase/squash_fixups_above_first_commit.go
Labels: enhancement

#3203 Show better keybinding suggestions
  pkg/commands/types/enums/enums.go
  pkg/gui/context.go
  pkg/gui/context/list_view_model.go
  pkg/gui/context/traits/list_cursor.go
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/confirmation_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/global_controller.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/menu_controller.go
  pkg/gui/controllers/merge_conflicts_controller.go
  pkg/gui/controllers/patch_building_controller.go
  pkg/gui/controllers/patch_explorer_controller.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/gui/controllers/remotes_controller.go
  pkg/gui/controllers/staging_controller.go
  pkg/gui/controllers/stash_controller.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/controllers/submodules_controller.go
  pkg/gui/controllers/tags_controller.go
  pkg/gui/controllers/worktrees_controller.go
  pkg/gui/filetree/commit_file_tree_view_model.go
  pkg/gui/filetree/file_tree.go
  pkg/gui/filetree/file_tree_view_model.go
  pkg/gui/layout.go
  pkg/gui/options_map.go
  pkg/gui/types/keybindings.go
  pkg/gui/views.go
  pkg/integration/components/common.go
  pkg/integration/components/views.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/ui/mode_specific_keybinding_suggestions.go
Labels: enhancement

#3271 Warn users when attempting to cherry pick with old key
  pkg/gui/controllers/basic_commits_controller.go
  pkg/i18n/english.go
Labels: ignore-for-release

#3259 Support selecting file range in patch builder
  pkg/commands/patch/patch_builder.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/filetree/commit_file_tree_view_model.go
  pkg/integration/tests/patch_building/move_range_to_index.go
  pkg/integration/tests/patch_building/toggle_range.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3266 Fix refreshing custom patch view when adding first file to custom patch
  pkg/gui/controllers/helpers/inline_status_helper.go
  pkg/gui/controllers/helpers/window_helper.go
  pkg/gui/main_panels.go
  pkg/integration/tests/patch_building/select_all_files.go
Labels: ignore-for-release

#3274 Add command to squash all fixups in the current branch
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  pkg/gui/controllers/local_commits_controller.go
  pkg/i18n/chinese.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/japanese.go
  pkg/i18n/korean.go
  pkg/i18n/polish.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/integration/tests/interactive_rebase/squash_fixups_above_first_commit.go
  pkg/integration/tests/interactive_rebase/squash_fixups_in_current_branch.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3283 Use slimmer scrollbars
  go.mod
  go.sum
  vendor/github.com/gdamore/tcell/v2/SECURITY.md
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/github.com/jesseduffield/gocui/scrollbar.go
  vendor/github.com/rivo/uniseg/README.md
  vendor/github.com/rivo/uniseg/eastasianwidth.go
  vendor/github.com/rivo/uniseg/emojipresentation.go
  vendor/github.com/rivo/uniseg/gen_breaktest.go
  vendor/github.com/rivo/uniseg/gen_properties.go
  vendor/github.com/rivo/uniseg/grapheme.go
  vendor/github.com/rivo/uniseg/graphemeproperties.go
  vendor/github.com/rivo/uniseg/graphemerules.go
  vendor/github.com/rivo/uniseg/line.go
  vendor/github.com/rivo/uniseg/lineproperties.go
  vendor/github.com/rivo/uniseg/linerules.go
  vendor/github.com/rivo/uniseg/properties.go
  vendor/github.com/rivo/uniseg/sentenceproperties.go
  vendor/github.com/rivo/uniseg/sentencerules.go
  vendor/github.com/rivo/uniseg/step.go
  vendor/github.com/rivo/uniseg/width.go
  vendor/github.com/rivo/uniseg/wordproperties.go
  vendor/github.com/rivo/uniseg/wordrules.go
  vendor/modules.txt
Labels: enhancement

#3240 Clear cherry-picked commits after pasting
  pkg/gui/controllers/helpers/cherry_pick_helper.go
  pkg/integration/tests/cherry_pick/cherry_pick.go
  pkg/integration/tests/cherry_pick/cherry_pick_conflicts.go
  pkg/integration/tests/cherry_pick/cherry_pick_during_rebase.go
  pkg/integration/tests/cherry_pick/cherry_pick_range.go
Labels: enhancement

#3287 Fix cherrypick demo
  pkg/integration/tests/demo/cherry_pick.go
Labels: maintenance
