Repository jesseduffield/lazygit, pull requests merged in 2024-07, with the labels that each got.

#3705 Fix running lazygit with a language other than English on Windows
  pkg/i18n/i18n.go
Labels: bug

#3706 Fix go generate on windows
  .gitattributes
  .gitignore
  docs/README.md
  vendor/github.com/kevinburke/ssh_config/.gitattributes
Labels: maintenance

#3707 Update translations from Crowdin
  pkg/i18n/english.go
  pkg/i18n/translations/ja.json
  pkg/i18n/translations/ko.json
  pkg/i18n/translations/nl.json
  pkg/i18n/translations/pl.json
  pkg/i18n/translations/ru.json
  pkg/i18n/translations/zh-CN.json
  pkg/i18n/translations/zh-TW.json
  scripts/update_language_files.sh
Labels: maintenance

#3712 Update tracking behaviour for branches created from remote branches
  pkg/commands/git_commands/branch.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/integration/tests/branch/new_branch_from_remote_tracking_different_name.go
  pkg/integration/tests/branch/new_branch_from_remote_tracking_same_name.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3541 Upgrade to Alpine Linux v3.19
  Dockerfile
Labels: enhancement

#3053 Add nerdfont icons for .bicep & .bicepparam files
  pkg/gui/presentation/icons/file_icons.go
Labels: enhancement

#3487 Allow setting a default name when creating new branches
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/integration/tests/commit/new_branch_with_prefix.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3594 Bump `actions/checkout`, `actions/setup-go`, `actions/cache/restore`, `actions/cache/save`
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/sponsors.yml
Labels: maintenance

#3599 Fix multi selection stage/discard not working for files with substrings
  pkg/gui/controllers/files_controller.go
  pkg/integration/tests/file/stage_children_range_select.go
  pkg/integration/tests/test_list.go
Labels: bug

#3656 Add flox install
  README.md
Labels: docs

#3647 Add Token credential request handling
  pkg/commands/oscommands/cmd_obj_runner.go
  pkg/commands/oscommands/cmd_obj_runner_test.go
  pkg/gui/controllers/helpers/credentials_helper.go
  pkg/i18n/english.go
Labels: enhancement

#3354 Switch between multiple log views
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  pkg/commands/git_commands/branch.go
  pkg/config/user_config.go
  pkg/i18n/english.go
  pkg/integration/tests/status/log_cmd.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement, requires-maintainer-signoff

#3284 Change RepoPaths to be acquired via RepoPathCache
  pkg/app/app.go
  pkg/commands/git_commands/repo_paths.go
  pkg/commands/git_commands/repo_paths_test.go
  pkg/commands/git_commands/status.go
  pkg/gui/dummies.go
  pkg/gui/recent_repos_panel.go
Labels: enhancement

#3484 Extend icon coverage on remotes and file extensions
  pkg/gui/presentation/icons/file_icons.go
  pkg/gui/presentation/icons/git_icons.go
Labels: enhancement

#3742 Check for fixup commits on CI
  .github/workflows/ci.yml
  scripts/check_for_fixups.sh
Labels: maintenance

#3025 Add support for setting the similarity threshold for detecting renames (closes #2904)
  .github/workflows/ci.yml
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
  pkg/commands/git_commands/file_loader.go
  pkg/commands/git_commands/file_loader_test.go
  pkg/commands/git_commands/stash.go
  pkg/commands/git_commands/stash_test.go
  pkg/commands/git_commands/working_tree.go
  pkg/commands/git_commands/working_tree_test.go
  pkg/config/app_config.go
  pkg/config/user_config.go
  pkg/gui/controllers.go
  pkg/gui/controllers/rename_similarity_threshold_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/diff/rename_similarity_threshold_change.go
  pkg/integration/tests/file/rename_similarity_threshold_change.go
  pkg/integration/tests/test_list.go
  schema/config.json
  scripts/check_for_fixups.sh
Labels: enhancement

#3744 Fix language auto detection
  pkg/i18n/i18n.go
  pkg/i18n/i18n_test.go
Labels: bug

#3745 Reapply "Check for fixup commits on CI"
  .github/workflows/ci.yml
  scripts/check_for_fixups.sh
Labels: maintenance
