Repository jesseduffield/lazygit, pull requests merged in 2024-04, with the labels that each got.

#3463 Add `spinner` config options
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/context/remotes_context.go
  pkg/gui/context/tags_context.go
  pkg/gui/controllers/helpers/app_status_helper.go
  pkg/gui/controllers/helpers/inline_status_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/remotes.go
  pkg/gui/presentation/status.go
  pkg/gui/presentation/tags.go
  pkg/gui/status/status_manager.go
  pkg/utils/utils.go
  schema/config.json
Labels: enhancement

#3481 pkg: fix some comment
  pkg/gui/dummies.go
  pkg/gui/gui.go
  pkg/theme/gocui.go
Labels: maintenance

#3482 Replace min/max helpers with built-in min/max
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/scroll_off_margin.go
  pkg/gui/filetree/file_tree.go
  pkg/gui/global_handlers.go
  pkg/gui/menu_panel.go
  pkg/gui/patch_exploring/focus.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/commits.go
  pkg/gui/presentation/graph/graph.go
  pkg/integration/components/shell.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: maintenance

#3478 Fix issue #3308
  pkg/commands/oscommands/cmd_obj_runner.go
Labels: bug

#3479 Fix stderr redirection
  pkg/gui/gui.go
Labels: ignore-for-release

#3309 Add StatusPanelView config
  docs/Config.md
  pkg/config/app_config.go
  pkg/config/user_config.go
  pkg/config/user_config_validation.go
  pkg/config/user_config_validation_test.go
  pkg/gui/controllers/status_controller.go
  schema/config.json
Labels: enhancement

#3493 sponsors.yml: Create PR instead of trying to push to a protected branch
  .github/workflows/sponsors.yml
Labels: maintenance

#3499 exclude sponsors PRs from release notes
  .github/workflows/sponsors.yml
Labels: ignore-for-release

#3364 pkg: fix some typos
  pkg/integration/components/test_driver.go
  pkg/integration/tests/custom_commands/form_prompts.go
  pkg/integration/tests/worktree/fast_forward_worktree_branch.go
Labels: maintenance

#3510 Fix amend to operation not working with non-HEAD merge commit
  pkg/utils/rebase_todo.go
  pkg/utils/rebase_todo_test.go
Labels: bug

#3456 Drop update-ref todos pointing to head
  .gitignore
  go.mod
  go.sum
  pkg/app/daemon/daemon.go
  pkg/app/daemon/rebase.go
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/git_commands/patch.go
  pkg/commands/git_commands/rebase.go
  pkg/commands/models/commit.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/presentation/commits.go
  pkg/gui/presentation/commits_test.go
  pkg/gui/services/custom_commands/session_state_loader.go
  pkg/integration/tests/branch/rebase_copied_branch.go
  pkg/integration/tests/interactive_rebase/drop_commit_in_copied_branch_with_update_ref.go
  pkg/integration/tests/interactive_rebase/interactive_rebase_of_copied_branch.go
  pkg/integration/tests/test_list.go
  pkg/utils/rebase_todo.go
  pkg/utils/rebase_todo_test.go
  vendor/github.com/stefanhaller/git-todo-parser/LICENSE
  vendor/github.com/stefanhaller/git-todo-parser/todo/parse.go
  vendor/github.com/stefanhaller/git-todo-parser/todo/todo.go
  vendor/github.com/stefanhaller/git-todo-parser/todo/write.go
  vendor/modules.txt
Labels: enhancement

#3523 Use errors.New instead of fmt.Errorf with no parameters
  pkg/commands/oscommands/copy.go
  pkg/utils/history_buffer.go
  pkg/utils/rebase_todo.go
  pkg/utils/yaml_utils/yaml_utils.go
Labels: maintenance

#3505 Add config options for length of commit hash displayed in commits view
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/presentation/commits.go
  schema/config.json
Labels: enhancement

#3535 chore: fix some comments and typos
  docs/Stacked_Branches.md
  pkg/commands/git_commands/working_tree.go
  pkg/gui/controllers/undo_controller.go
  pkg/gui/filetree/build_tree_test.go
Labels: maintenance

#3537 Enable the commit graph in the divergence view
  pkg/gui/context/sub_commits_context.go
  pkg/gui/presentation/commits.go
  pkg/gui/presentation/commits_test.go
Labels: enhancement
