Repository jesseduffield/lazygit, pull requests merged in 2024-09, with the labels that each got.

#3870 Make auto-staging resolved conflicts optional
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/filetree/file_node.go
  pkg/integration/tests/conflicts/resolve_no_auto_stage.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3879 Ask to auto-stage unstaged files when continuing a rebase after resolving conflicts
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/rebase_conflicts_fix_build_errors.go
  pkg/integration/tests/file/discard_all_dir_changes.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3878 Don't allow opening a menu while the search or filter prompt is open
  pkg/gui/controllers/helpers/search_helper.go
  pkg/gui/gui_common.go
  pkg/gui/keybindings.go
  pkg/gui/types/common.go
Labels: bug

#3871 Offer autostash option when creating new branch
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/integration/tests/branch/checkout_autostash.go
  pkg/integration/tests/branch/new_branch_autostash.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3886 Add Zed editor support to editorPreset
  docs/Config.md
  pkg/config/editor_presets.go
  pkg/config/user_config.go
  schema/config.json
Labels: enhancement

#3888 Switch to Files panel after popping a stash
  pkg/gui/controllers/stash_controller.go
  pkg/integration/tests/stash/apply.go
  pkg/integration/tests/stash/pop.go
Labels: enhancement

#3898 Update language files from Crowdin
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/i18n/translations/zh-CN.json
  pkg/i18n/translations/zh-TW.json
Labels: i18n

#3892 With stacked branches, create fixup commit at the end of the branch it belongs to
  pkg/app/daemon/daemon.go
  pkg/commands/git_commands/rebase.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/integration/tests/commit/create_fixup_commit_in_branch_stack.go
  pkg/integration/tests/test_list.go
  pkg/utils/rebase_todo.go
  pkg/utils/rebase_todo_test.go
Labels: enhancement

#3913 Add options for disabling switching to the Files panel after popping or applying a stash
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/stash_controller.go
  schema/config.json
Labels: enhancement

#3919 Improve performance with large numbers of untracked or modified files
  pkg/gui/filetree/build_tree.go
Labels: bug

#3918 Fix crash when viewing the divergence of a branch which is up to date with its upstream
  pkg/gui/context/list_renderer.go
  pkg/integration/tests/branch/show_divergence_from_upstream_no_divergence.go
  pkg/integration/tests/test_list.go
Labels: bug

#3936 Fix copying commit author to clipboard
  pkg/commands/git_commands/commit.go
  pkg/integration/tests/commit/copy_author_to_clipboard.go
  pkg/integration/tests/test_list.go
Labels: bug

#3915 Better branch delete confirmation
  pkg/commands/git_commands/branch.go
  pkg/gui/controllers.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/branches_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/delete.go
  pkg/integration/tests/branch/delete_remote_branch_with_different_name.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3916 Add a menu item to delete both local and remote branch at once
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/branches_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/delete.go
Labels: enhancement

#3914 Auto-render hyperlinks
  go.mod
  go.sum
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/confirmation_helper_test.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/views.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: enhancement
