Repository jesseduffield/lazygit, pull requests merged in 2024-02, with the labels that each got.

#3316 Disallow cherry-picking merge commits
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/controllers/helpers/cherry_pick_helper.go
  pkg/i18n/english.go
Labels: bug

#3276 Support range select removing files from a commit
  pkg/commands/git_commands/rebase.go
  pkg/commands/git_commands/rebase_test.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/i18n/english.go
  pkg/i18n/russian.go
  pkg/integration/tests/commit/discard_old_file_change.go
  pkg/integration/tests/commit/discard_old_file_changes.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3290 Fix two problems related to update-ref rebase todo items
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/switch_to_diff_files_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/interactive_rebase/view_files_of_todo_entries.go
  pkg/integration/tests/test_list.go
Labels: bug

#3197 Migrate git.log.showGraph and git.log.order to app state
  docs/Config.md
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/config/app_config.go
  pkg/config/user_config.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/integration/tests/bisect/basic.go
  pkg/integration/tests/bisect/choose_terms.go
  pkg/integration/tests/bisect/skip.go
  pkg/integration/tests/cherry_pick/cherry_pick_during_rebase.go
  pkg/integration/tests/commit/highlight.go
  pkg/integration/tests/interactive_rebase/drop_todo_commit_with_update_ref.go
  pkg/integration/tests/interactive_rebase/quick_start_keep_selection.go
  pkg/integration/tests/interactive_rebase/quick_start_keep_selection_range.go
  pkg/integration/tests/interactive_rebase/view_files_of_todo_entries.go
  pkg/integration/tests/reflog/do_not_show_branch_markers_in_reflog_subcommits.go
  schema/config.json
Labels: enhancement

#3286 Fix order of custom commands history
  pkg/gui/controllers/custom_command_action.go
  pkg/integration/tests/custom_commands/history.go
  pkg/integration/tests/test_list.go
Labels: bug

#3285 Fix initial scroll bar size again
  pkg/gui/view_helpers.go
Labels: ignore-for-release

#3282 Keep sort order when filtering lists sorted by date
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .golangci.yml
  Dockerfile
  go.mod
  go.sum
  pkg/gui/context/branches_context.go
  pkg/gui/context/filtered_list.go
  pkg/gui/context/filtered_list_view_model.go
  pkg/gui/context/menu_context.go
  pkg/gui/context/reflog_commits_context.go
  pkg/gui/context/remote_branches_context.go
  pkg/gui/context/remotes_context.go
  pkg/gui/context/stash_context.go
  pkg/gui/context/submodules_context.go
  pkg/gui/context/tags_context.go
  pkg/gui/context/worktrees_context.go
  pkg/integration/tests/filter_and_search/filter_menu.go
  pkg/integration/tests/filter_and_search/filter_menu_cancel_filter_with_escape.go
  pkg/integration/tests/filter_and_search/filter_updates_when_model_changes.go
Labels: enhancement

#2936 Use $XDG_STATE_HOME for state.yml
  docs/Config.md
  go.mod
  go.sum
  pkg/config/app_config.go
  vendor/github.com/OpenPeeDeeP/xdg/.gitignore
  vendor/github.com/OpenPeeDeeP/xdg/LICENSE
  vendor/github.com/OpenPeeDeeP/xdg/README.md
  vendor/github.com/OpenPeeDeeP/xdg/appveyor.yml
  vendor/github.com/OpenPeeDeeP/xdg/xdg.go
  vendor/github.com/OpenPeeDeeP/xdg/xdg_bsd.go
  vendor/github.com/OpenPeeDeeP/xdg/xdg_darwin.go
  vendor/github.com/OpenPeeDeeP/xdg/xdg_linux.go
  vendor/github.com/OpenPeeDeeP/xdg/xdg_windows.go
  vendor/github.com/adrg/xdg/CODE_OF_CONDUCT.md
  vendor/github.com/adrg/xdg/CONTRIBUTING.md
  vendor/github.com/adrg/xdg/LICENSE
  vendor/github.com/adrg/xdg/README.md
  vendor/github.com/adrg/xdg/base_dirs.go
  vendor/github.com/adrg/xdg/codecov.yml
  vendor/github.com/adrg/xdg/doc.go
  vendor/github.com/adrg/xdg/internal/pathutil/pathutil.go
  vendor/github.com/adrg/xdg/internal/pathutil/pathutil_plan9.go
  vendor/github.com/adrg/xdg/internal/pathutil/pathutil_unix.go
  vendor/github.com/adrg/xdg/internal/pathutil/pathutil_windows.go
  vendor/github.com/adrg/xdg/paths_darwin.go
  vendor/github.com/adrg/xdg/paths_plan9.go
  vendor/github.com/adrg/xdg/paths_unix.go
  vendor/github.com/adrg/xdg/paths_windows.go
  vendor/github.com/adrg/xdg/user_dirs.go
  vendor/github.com/adrg/xdg/xdg.go
  vendor/modules.txt
Labels: bug

#3264 Change "git reset" default to --mixed
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/i18n/english.go
Labels: enhancement

#3302 Add author filtering to commit view
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/reflog_commit_loader.go
  pkg/commands/git_commands/reflog_commit_loader_test.go
  pkg/gui/controllers/filtering_menu_action.go
  pkg/gui/controllers/helpers/mode_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/sub_commits_helper.go
  pkg/gui/gui.go
  pkg/gui/modes/filtering/filtering.go
  pkg/i18n/english.go
  pkg/integration/tests/filter_by_author/select_author.go
  pkg/integration/tests/filter_by_author/shared.go
  pkg/integration/tests/filter_by_author/type_author.go
  pkg/integration/tests/test_list.go
Labels: enhancement
