Repository jesseduffield/lazygit, pull requests merged in 2024-06, with the labels that each got.

#3619 Fix pushing to branch when upstream not stored locally
  pkg/commands/git_commands/sync.go
  pkg/commands/git_commands/sync_test.go
  pkg/commands/models/branch.go
  pkg/gui/controllers/sync_controller.go
  pkg/i18n/chinese.go
  pkg/i18n/english.go
  pkg/i18n/korean.go
  pkg/i18n/polish.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/integration/tests/sync/force_push_remote_branch_not_stored_locally.go
  pkg/integration/tests/test_list.go
Labels: bug

#3623 Add user config `gui.expandedSidePanelWeight`
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/window_arrangement_helper.go
  pkg/gui/controllers/helpers/window_arrangement_helper_test.go
  schema/config.json
Labels: enhancement

#3602 Improve the "Find base commit for fixup" command
  docs/Fixup_Commits.md
  docs/dev/Find_Base_Commit_For_Fixup_Design.md
  docs/dev/README.md
  go.mod
  go.sum
  pkg/gui/controllers/helpers/fixup_helper.go
  pkg/gui/controllers/helpers/fixup_helper_test.go
  pkg/i18n/english.go
  pkg/i18n/polish.go
  pkg/integration/tests/commit/find_base_commit_for_fixup_only_added_lines.go
  pkg/integration/tests/test_list.go
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/modules.txt
Labels: enhancement

#3630 (#3618) Fix pushing a branch to remote with a different name causing error
  pkg/commands/git_commands/sync.go
  pkg/commands/git_commands/sync_test.go
Labels: bug

#3613 Divergence from base branch display
  docs/Config.md
  pkg/commands/git_commands/branch_loader.go
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/git_commands/main_branches.go
  pkg/commands/models/branch.go
  pkg/config/user_config.go
  pkg/config/user_config_validation.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/sub_commits_helper.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/gui.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/branches_test.go
  pkg/gui/presentation/status.go
  pkg/gui/types/common.go
  pkg/integration/tests/branch/delete_remote_branch_with_credential_prompt.go
  pkg/integration/tests/status/show_divergence_from_base_branch.go
  pkg/integration/tests/sync/force_push.go
  pkg/integration/tests/sync/force_push_multiple_matching.go
  pkg/integration/tests/sync/force_push_multiple_upstream.go
  pkg/integration/tests/sync/pull.go
  pkg/integration/tests/sync/pull_and_set_upstream.go
  pkg/integration/tests/sync/pull_merge.go
  pkg/integration/tests/sync/pull_merge_conflict.go
  pkg/integration/tests/sync/pull_rebase.go
  pkg/integration/tests/sync/pull_rebase_conflict.go
  pkg/integration/tests/sync/pull_rebase_interactive_conflict.go
  pkg/integration/tests/sync/pull_rebase_interactive_conflict_drop.go
  pkg/integration/tests/sync/push.go
  pkg/integration/tests/sync/push_and_auto_set_upstream.go
  pkg/integration/tests/sync/push_and_set_upstream.go
  pkg/integration/tests/sync/push_follow_tags.go
  pkg/integration/tests/sync/push_no_follow_tags.go
  pkg/integration/tests/sync/push_with_credential_prompt.go
  pkg/integration/tests/sync/shared.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3614 Add command to show divergence from base branch as a left-right log
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/branches_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/show_divergence_from_base_branch.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3615 Add command to rebase onto base branch
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/i18n/english.go
  pkg/i18n/polish.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/integration/tests/branch/rebase.go
  pkg/integration/tests/branch/rebase_abort_on_conflict.go
  pkg/integration/tests/branch/rebase_and_drop.go
  pkg/integration/tests/branch/rebase_cancel_on_conflict.go
  pkg/integration/tests/branch/rebase_copied_branch.go
  pkg/integration/tests/branch/rebase_does_not_autosquash.go
  pkg/integration/tests/branch/rebase_from_marked_base.go
  pkg/integration/tests/branch/rebase_onto_base_branch.go
  pkg/integration/tests/branch/rebase_to_upstream.go
  pkg/integration/tests/interactive_rebase/advanced_interactive_rebase.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3634 Make profiling easier
  CONTRIBUTING.md
  docs/dev/Profiling.md
  docs/dev/README.md
  pkg/app/entry_point.go
Labels: maintenance

#3636 Update `rebase_onto` demo test to match new the rebase menu title
  pkg/integration/tests/demo/rebase_onto.go
Labels: maintenance

#3640 Include demos when running integration tests on CI
  pkg/gui/gui_driver.go
  pkg/gui/test_mode.go
  pkg/integration/clients/go_test.go
  pkg/integration/components/test_test.go
  pkg/integration/components/view_driver.go
  pkg/integration/types/types.go
Labels: maintenance

#3637 Fix secondary window resize
  pkg/gui/controllers/helpers/window_arrangement_helper.go
  pkg/integration/components/view_driver.go
  pkg/integration/tests/staging/diff_change_screen_mode.go
  pkg/integration/tests/test_list.go
Labels: bug

#3587 Support range select for amending commit attributes
  pkg/commands/git_commands/rebase.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/integration/tests/commit/add_co_author_range.go
  pkg/integration/tests/commit/reset_author_range.go
  pkg/integration/tests/commit/set_author_range.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3645 Improve "Find base commit for fixup" command when there are changes for master commits
  pkg/gui/controllers/helpers/fixup_helper.go
  pkg/integration/tests/commit/find_base_commit_for_fixup_disregard_main_branch.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3654 Show "exec" todos in the list of rebase todos
  pkg/commands/git_commands/commit_loader.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/interactive_rebase/show_exec_todos.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3662 Fix reporting of unexpected selections in integration tests
  pkg/integration/components/view_driver.go
Labels: maintenance

#3625 Add user config gui.commitAuthorFormat
  docs/Config.md
  pkg/config/user_config.go
  pkg/config/user_config_validation.go
  pkg/gui/presentation/commits.go
  schema/config.json
Labels: enhancement

#3687 Reduce memory consumption when loading large number of commits
  go.mod
  go.sum
  pkg/gui/background.go
  pkg/gui/context/base_context.go
  pkg/gui/context/list_context_trait.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/remote_branches_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/context/view_trait.go
  pkg/gui/controllers/list_controller.go
  pkg/gui/layout.go
  pkg/gui/types/context.go
  pkg/integration/components/view_driver.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: enhancement

#3685 Fix truncation of branch names containing non-ASCII characters
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/branches_test.go
  pkg/utils/formatting.go
  pkg/utils/formatting_test.go
Labels: bug

#3660 Fix duplicate keybinding suggestions in status bar after switching repos
  pkg/gui/context/base_context.go
  pkg/gui/controllers.go
  pkg/gui/types/context.go
  pkg/integration/components/shell.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/ui/keybinding_suggestions_when_switching_repos.go
Labels: bug

#3652 Add prompt to the remote branch checkout menu
  pkg/gui/context/menu_context.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/menu_panel.go
  pkg/gui/types/common.go
  pkg/i18n/english.go
Labels: enhancement

#3658 Fix PTY layout problems
  pkg/gui/gui.go
  pkg/gui/gui_common.go
  pkg/gui/main_panels.go
  pkg/gui/pty.go
Labels: bug

#3683 Always show the "Discard unchanged changes" menu item
  pkg/gui/controllers/files_controller.go
  pkg/i18n/english.go
Labels: enhancement

#3628 Show current value in menus
  pkg/gui/context/menu_context.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/gui/types/common.go
  pkg/integration/tests/branch/sort_local_branches.go
  pkg/integration/tests/branch/sort_remote_branches.go
Labels: enhancement

#3686 Improve render performance
  pkg/gui/context/base_context.go
  pkg/gui/context/branches_context.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/reflog_commits_context.go
  pkg/gui/context/remote_branches_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/controllers/helpers/window_arrangement_helper.go
  pkg/gui/controllers/screen_mode_actions.go
  pkg/gui/information_panel.go
  pkg/gui/layout.go
  pkg/gui/presentation/branches.go
  pkg/gui/types/context.go
  pkg/utils/formatting.go
  pkg/utils/formatting_test.go
Labels: bug, performance

#3667 Fix wrong highlight in staging panel when entering file with only staged changes
  docs/Config.md
  go.mod
  go.sum
  pkg/config/user_config.go
  pkg/gui/context.go
  pkg/gui/context/simple_context.go
  pkg/gui/context/view_trait.go
  pkg/gui/gui.go
  pkg/gui/layout.go
  pkg/gui/views.go
  pkg/theme/theme.go
  schema/config.json
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: bug

#3649 Convert TranslationSets to json
  cmd/i18n/main.go
  pkg/cheatsheet/generate.go
  pkg/cheatsheet/generate_test.go
  pkg/commands/hosting_service/hosting_service_test.go
  pkg/i18n/chinese.go
  pkg/i18n/dutch.go
  pkg/i18n/english.go
  pkg/i18n/i18n.go
  pkg/i18n/japanese.go
  pkg/i18n/korean.go
  pkg/i18n/polish.go
  pkg/i18n/russian.go
  pkg/i18n/traditional_chinese.go
  pkg/i18n/translations/ja.json
  pkg/i18n/translations/ko.json
  pkg/i18n/translations/nl.json
  pkg/i18n/translations/pl.json
  pkg/i18n/translations/ru.json
  pkg/i18n/translations/zh-CN.json
  pkg/i18n/translations/zh-TW.json
  pkg/utils/dummies.go
Labels: maintenance

#3676 Add command to paste commit message from clipboard
  docs/Config.md
  pkg/commands/oscommands/os.go
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/commit/paste_commit_message.go
  pkg/integration/tests/commit/paste_commit_message_over_existing.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3694 Stagger popup panels
  go.mod
  go.sum
  pkg/gui/context.go
  pkg/gui/context/commit_message_context.go
  pkg/gui/controllers.go
  pkg/gui/controllers/commit_description_controller.go
  pkg/gui/controllers/commit_message_controller.go
  pkg/gui/controllers/custom_patch_options_menu_action.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/gui_common.go
  pkg/gui/layout.go
  pkg/gui/types/common.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/modules.txt
Labels: enhancement

#3697 Always reapply filters on filtered views when model changes, even inactive ones
  pkg/gui/controllers/helpers/search_helper.go
  pkg/integration/tests/filter_and_search/filter_updates_when_model_changes.go
Labels: bug

#3696 Turn off the highlight of the suggestions panel when it loses focus
  pkg/gui/controllers/suggestions_controller.go
Labels: bug

#3688 Make commit author length configurable, take 2
  docs/Config.md
  pkg/config/user_config.go
  pkg/config/user_config_validation.go
  pkg/gui/presentation/authors/authors.go
  pkg/gui/presentation/authors/authors_test.go
  pkg/gui/presentation/commits.go
  schema/config.json
Labels: enhancement

#3566 Add Squash merge
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/branch.go
  pkg/config/user_config.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/squash_merge.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/ui/mode_specific_keybinding_suggestions.go
  schema/config.json
Labels: feature

#3691 Make opening git difftool more consistent
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/diff_helper.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/gui/controllers/tags_controller.go
Labels: enhancement
