Repository jesseduffield/lazygit, pull requests merged in 2024-08, with the labels that each got.

#3784 feat(custom command): support multiple contexts within one command
  docs/Custom_Command_Keybindings.md
  pkg/gui/services/custom_commands/client.go
  pkg/gui/services/custom_commands/keybinding_creator.go
  pkg/integration/tests/custom_commands/global_context.go
  pkg/integration/tests/custom_commands/multiple_contexts.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3779 Don't exit app when GetRepoPaths call fails during startup
  pkg/app/app.go
Labels: bug

#3810 Fix lack of icon assignation when extension don't match capitalization (lowercase)
  pkg/gui/presentation/icons/file_icons.go
Labels: bug

#3815 Allow GPG reword for last commit
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
  pkg/commands/git_commands/rebase.go
  pkg/gui/controllers/local_commits_controller.go
Labels: bug

#3793 Allow using shell aliases in interactive custom commands
  pkg/commands/git_cmd_obj_builder.go
  pkg/commands/oscommands/cmd_obj_builder.go
  pkg/commands/oscommands/dummies.go
  pkg/commands/oscommands/os.go
  pkg/commands/oscommands/os_default_platform.go
  pkg/commands/oscommands/os_windows.go
  pkg/gui/controllers/custom_command_action.go
Labels: enhancement

#3794 Switch tabs with panel jump keys
  pkg/gui/controllers.go
  pkg/gui/controllers/jump_to_side_window_controller.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/ui/switch_tab_with_panel_jump_keys.go
Labels: enhancement

#3820 Fix line coloring when using the delta pager
  go.mod
  go.sum
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: bug

#3800 Rename "Custom Command" to "Shell Command"
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/config/app_config.go
  pkg/config/user_config.go
  pkg/gui/controllers/global_controller.go
  pkg/gui/controllers/shell_command_action.go
  pkg/i18n/english.go
  pkg/integration/tests/custom_commands/basic_command.go
  pkg/integration/tests/filter_and_search/filter_updates_when_model_changes.go
  pkg/integration/tests/shell_commands/basic_shell_command.go
  pkg/integration/tests/shell_commands/complex_shell_command.go
  pkg/integration/tests/shell_commands/delete_from_history.go
  pkg/integration/tests/shell_commands/edit_history.go
  pkg/integration/tests/shell_commands/history.go
  pkg/integration/tests/shell_commands/omit_from_history.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3808 Some cleanups for APIs related to contexts
  pkg/gui/context.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/menu_context.go
  pkg/gui/context/parent_context_mgr.go
  pkg/gui/context/patch_explorer_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/controllers/commit_description_controller.go
  pkg/gui/controllers/commit_message_controller.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/confirmation_controller.go
  pkg/gui/controllers/context_lines_controller.go
  pkg/gui/controllers/custom_patch_options_menu_action.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/filtering_menu_action.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/diff_helper.go
  pkg/gui/controllers/helpers/fixup_helper.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/helpers/merge_conflicts_helper.go
  pkg/gui/controllers/helpers/patch_building_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/helpers/search_helper.go
  pkg/gui/controllers/helpers/staging_helper.go
  pkg/gui/controllers/helpers/sub_commits_helper.go
  pkg/gui/controllers/helpers/window_arrangement_helper.go
  pkg/gui/controllers/helpers/window_helper.go
  pkg/gui/controllers/jump_to_side_window_controller.go
  pkg/gui/controllers/list_controller.go
  pkg/gui/controllers/menu_controller.go
  pkg/gui/controllers/merge_conflicts_controller.go
  pkg/gui/controllers/options_menu_action.go
  pkg/gui/controllers/patch_explorer_controller.go
  pkg/gui/controllers/quit_actions.go
  pkg/gui/controllers/remotes_controller.go
  pkg/gui/controllers/rename_similarity_threshold_controller.go
  pkg/gui/controllers/side_window_controller.go
  pkg/gui/controllers/snake_controller.go
  pkg/gui/controllers/staging_controller.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/controllers/submodules_controller.go
  pkg/gui/controllers/suggestions_controller.go
  pkg/gui/controllers/switch_to_diff_files_controller.go
  pkg/gui/controllers/tags_controller.go
  pkg/gui/controllers/toggle_whitespace_action.go
  pkg/gui/extras_panel.go
  pkg/gui/global_handlers.go
  pkg/gui/gui.go
  pkg/gui/gui_common.go
  pkg/gui/gui_driver.go
  pkg/gui/layout.go
  pkg/gui/menu_panel.go
  pkg/gui/options_map.go
  pkg/gui/types/common.go
  pkg/gui/types/context.go
  pkg/gui/view_helpers.go
Labels: maintenance

#3809 Improve template placeholders for custom commands
  docs/Custom_Command_Keybindings.md
  pkg/gui/context.go
  pkg/gui/services/custom_commands/session_state_loader.go
  pkg/gui/types/context.go
  pkg/integration/tests/custom_commands/selected_commit.go
  pkg/integration/tests/custom_commands/selected_path.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3828 Fix pressing escape after clicking in diff view
  pkg/gui/patch_exploring/state.go
Labels: bug

#3807 Specifying branch name source from refs/heads for fast forwarding
  pkg/commands/git_commands/sync.go
Labels: bug

#3853 Improve fixup commits script
  .github/workflows/ci.yml
  scripts/check_for_fixups.sh
Labels: maintenance

#3631 Fix range select -> stage failure when deleted file is already staged
  pkg/gui/controllers/files_controller.go
  pkg/integration/tests/file/stage_deleted_range_select.go
  pkg/integration/tests/test_list.go
Labels: bug

#3825 Support hyperlinks from pagers
  docs/Custom_Pagers.md
  go.mod
  go.sum
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/confirmation_helper_test.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/global_handlers.go
  pkg/gui/gui.go
  pkg/gui/gui_common.go
  pkg/gui/information_panel.go
  pkg/gui/keybindings.go
  pkg/gui/style/hyperlink.go
  pkg/gui/types/common.go
  pkg/gui/view_helpers.go
  pkg/i18n/english.go
  pkg/integration/tests/ui/open_link_failure.go
  pkg/utils/color.go
  pkg/utils/color_test.go
  vendor/github.com/jesseduffield/gocui/escape.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/github.com/jesseduffield/gocui/tcell_driver.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: enhancement

#3839 Scroll views up if needed to show all their content
  go.mod
  go.sum
  pkg/gui/context/base_context.go
  pkg/gui/context/list_context_trait.go
  pkg/gui/layout.go
  pkg/gui/types/context.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: bug

#3838 Fix crash when filtering commits
  pkg/gui/context/local_commits_context.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/presentation/commits.go
  pkg/utils/formatting.go
Labels: bug

#3837 Allow using `<`/`>` and `,`/`.` in sticky range select mode in patch explorer
  pkg/gui/controllers/patch_explorer_controller.go
  pkg/gui/patch_exploring/state.go
  pkg/integration/tests/ui/range_select.go
Labels: bug

#3835 Fix loading customCommands from per-repo config file
  pkg/config/app_config.go
  pkg/integration/components/file_system.go
  pkg/integration/tests/config/custom_commands_in_per_repo_config.go
  pkg/integration/tests/test_list.go
Labels: bug

#3855 Fix rendering regression introduced in #3839
  go.mod
  go.sum
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: ignore-for-release

#3856 Underline hyperlinks only on mouse hover
  go.mod
  go.sum
  pkg/gui/views.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/github.com/jesseduffield/gocui/tcell_driver.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: enhancement

#3864 Add missing closing quote in pager docs
  docs/Custom_Pagers.md
Labels: ignore-for-release

#3860 Fix cancelled autostash resulting in stuck inline status
  pkg/gui/controllers/helpers/refs_helper.go
Labels: bug

#3854 Fix linter warnings
  .github/workflows/ci.yml
  .golangci.yml
  pkg/commands/git_config/cached_git_config.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/gui.go
  pkg/gui/services/custom_commands/handler_creator.go
  pkg/integration/clients/cli.go
  pkg/integration/clients/tui.go
Labels: maintenance

#3751 Add codespell support (config, workflow to detect/not fix) and make it fix few typos
  .codespellrc
  .github/workflows/codespell.yml
  .gitignore
  docs/dev/Codebase_Guide.md
  docs/dev/Find_Base_Commit_For_Fixup_Design.md
  pkg/commands/oscommands/cmd_obj_runner.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/confirmation_helper_test.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/types/context.go
  pkg/i18n/english.go
  pkg/integration/components/text_matcher.go
  pkg/integration/components/view_driver.go
  pkg/integration/tests/branch/rebase_and_drop.go
  pkg/integration/tests/demo/custom_patch.go
  pkg/integration/tests/filter_and_search/nested_filter_transient.go
  pkg/integration/tests/misc/recent_repos_on_launch.go
  scripts/bisect.sh
Labels: maintenance

#3869 Non-sticky range selection diff
  pkg/commands/models/branch.go
  pkg/commands/models/commit.go
  pkg/commands/models/remote_branch.go
  pkg/commands/models/stash_entry.go
  pkg/commands/models/tag.go
  pkg/gui/context/commit_files_context.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/reflog_commits_context.go
  pkg/gui/context/stash_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/controllers.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/helpers/diff_helper.go
  pkg/gui/controllers/helpers/patch_building_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/sub_commits_controller.go
  pkg/gui/controllers/switch_to_diff_files_controller.go
  pkg/gui/controllers/types.go
  pkg/gui/filetree/commit_file_tree_view_model.go
  pkg/gui/types/ref.go
  pkg/i18n/english.go
  pkg/integration/tests/diff/diff.go
  pkg/integration/tests/diff/diff_and_apply_patch.go
  pkg/integration/tests/diff/diff_non_sticky_range.go
  pkg/integration/tests/test_list.go
Labels: enhancement
