Repository jesseduffield/lazygit, pull requests merged in 2025-07, with the labels that each got.

#4673 Show stash name for selected stash
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/diff_helper.go
  pkg/gui/controllers/stash_controller.go
  pkg/gui/types/rendering.go
Labels: enhancement

#4661 Collapse selection after deleting a range of branches or stashes
  pkg/gui/context/traits/list_cursor.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/branches_helper.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/gui/controllers/stash_controller.go
Labels: bug

#4685 Add user config to use hunk mode by default when entering staging view
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/patch_building_helper.go
  pkg/gui/controllers/helpers/staging_helper.go
  pkg/gui/controllers/patch_building_controller.go
  pkg/gui/controllers/staging_controller.go
  pkg/gui/patch_exploring/state.go
  schema/config.json
Labels: enhancement

#4690 Fix broken markdown in auto-generated keybindings documentation
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_pt.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/cheatsheet/generate.go
Labels: docs

#4697 Try using PAT on sponsors CI
  .github/workflows/sponsors.yml
Labels: maintenance

#4702 README.md: Update Sponsors
  README.md
Labels: ignore-for-release

#4703 Update release workflow
  .github/workflows/release.yml
  .goreleaser.yml
Labels: maintenance

#4705 Remove the homebrew tap from the readme
  README.md
Labels: docs

#4709 Fix scrolling hunk into view when selecting next hunk
  pkg/gui/context/list_context_trait.go
  pkg/gui/context/patch_explorer_context.go
  pkg/gui/patch_exploring/focus.go
  pkg/gui/types/context.go
Labels: bug

#4715 Remove unused code and texts
  pkg/app/daemon/rebase.go
  pkg/commands/oscommands/cmd_obj_builder.go
  pkg/gui/context_config.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/i18n/english.go
Labels: maintenance

#4725 Detect double-clicks properly
  go.mod
  go.sum
  pkg/gui/context/base_context.go
  pkg/gui/context/simple_context.go
  pkg/gui/controllers.go
  pkg/gui/controllers/list_controller.go
  pkg/gui/types/context.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_loong64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/modules.txt
Labels: bug

#4726 Improve mouse handling of suggestions panel
  pkg/gui/context/suggestions_context.go
  pkg/gui/controllers/commit_description_controller.go
  pkg/gui/controllers/commit_message_controller.go
  pkg/gui/controllers/confirmation_controller.go
  pkg/gui/controllers/helpers/suggestions_helper.go
  pkg/gui/controllers/suggestions_controller.go
  pkg/gui/keybindings.go
Labels: enhancement

#4730 Fix commit searching during rebase or in divergence from upstream view
  pkg/gui/context/list_renderer.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/sub_commits_context.go
Labels: bug

#4728 Add new command "Checkout previous branch"
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_pt.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/config/user_config.go
  pkg/gui/controllers/branches_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/checkout_previous_branch.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#4749 Several small fixes to filtering mode (by path or author)
  pkg/commands/git_commands/stash_loader.go
  pkg/gui/controllers/filtering_menu_action.go
  pkg/gui/controllers/helpers/mode_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/integration/tests/stash/filter_by_path.go
  pkg/integration/tests/test_list.go
Labels: bug

#4750 Show diff for renamed file when filtering by path
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/git_commands/commit_loading_shared.go
  pkg/commands/git_commands/commit_test.go
  pkg/commands/git_commands/reflog_commit_loader.go
  pkg/commands/git_commands/reflog_commit_loader_test.go
  pkg/commands/models/commit.go
  pkg/gui/controllers.go
  pkg/gui/controllers/helpers/diff_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/sub_commits_helper.go
  pkg/gui/controllers/reflog_commits_controller.go
  pkg/gui/controllers/undo_controller.go
  pkg/gui/types/common.go
  pkg/integration/components/shell.go
  pkg/integration/tests/filter_by_path/show_diffs_for_renamed_file.go
  pkg/integration/tests/test_list.go
Labels: bug

#4758 Don't use hunk mode for added or deleted files even when useHunkModeInStagingView config is on
  pkg/commands/patch/patch.go
  pkg/commands/patch/patch_test.go
  pkg/gui/patch_exploring/state.go
Labels: enhancement

#4754 Show [0] keybinding in main view title
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_pt.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/gui/controllers.go
  pkg/gui/controllers/options_menu_action.go
  pkg/gui/controllers/switch_to_focused_main_view_controller.go
  pkg/gui/keybindings/keybindings.go
  pkg/gui/views.go
Labels: enhancement

#4756 Allow rewording or dropping commits in filtering mode
  pkg/gui/controllers/local_commits_controller.go
  pkg/integration/tests/filter_by_path/drop_commit_in_filtering_mode.go
  pkg/integration/tests/filter_by_path/keep_same_commit_selected_on_exit.go
  pkg/integration/tests/filter_by_path/reword_commit_in_filtering_mode.go
  pkg/integration/tests/filter_by_path/shared.go
  pkg/integration/tests/test_list.go
Labels: bug

#4778 Make the minimum required git version a placeholder in the error text
  pkg/app/app.go
  pkg/app/errors.go
  pkg/i18n/english.go
Labels: maintenance

#4779 When pressing `a` to stage all files, don't include untracked files when showing only tracked files
  pkg/commands/git_commands/working_tree.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/fixup_helper.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/integration/tests/filter_and_search/stage_all_stages_only_tracked_files_in_tracked_only_filter.go
  pkg/integration/tests/test_list.go
Labels: bug
