Repository jesseduffield/lazygit, pull requests merged in 2025-04, with the labels that each got.

#4317 Fix discarding submodule changes in nested folders
  go.mod
  go.sum
  pkg/gui/controllers/files_controller.go
  pkg/gui/filetree/node.go
  pkg/i18n/english.go
  pkg/integration/components/shell.go
  pkg/integration/tests/submodule/remove.go
  pkg/integration/tests/submodule/reset.go
  pkg/integration/tests/submodule/reset_folder.go
  pkg/integration/tests/test_list.go
  vendor/github.com/jesseduffield/generics/set/set.go
  vendor/modules.txt
Labels: bug

#4425 Update kidpix link in README to active url
  README.md
Labels: docs

#4454 Fix hyperlinks in last line of confirmation popups
  go.mod
  go.sum
  pkg/gui/views.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: bug

#4449 Some code cleanup
  pkg/gui/context.go
  pkg/gui/controllers/custom_patch_options_menu_action.go
  pkg/gui/controllers/filtering_menu_action.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/helpers/files_helper.go
  pkg/gui/controllers/helpers/fixup_helper.go
  pkg/gui/controllers/helpers/host_helper.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/helpers/merge_conflicts_helper.go
  pkg/gui/controllers/helpers/patch_building_helper.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/helpers/search_helper.go
  pkg/gui/controllers/helpers/staging_helper.go
  pkg/gui/controllers/helpers/sub_commits_helper.go
  pkg/gui/controllers/helpers/suggestions_helper.go
  pkg/gui/controllers/helpers/upstream_helper.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/gui/controllers/helpers/worktree_helper.go
  pkg/gui/controllers/jump_to_side_window_controller.go
  pkg/gui/controllers/list_controller.go
  pkg/gui/controllers/quit_actions.go
  pkg/gui/controllers/remotes_controller.go
  pkg/gui/controllers/side_window_controller.go
  pkg/gui/controllers/snake_controller.go
  pkg/gui/controllers/staging_controller.go
  pkg/gui/controllers/stash_controller.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/controllers/submodules_controller.go
  pkg/gui/controllers/switch_to_diff_files_controller.go
  pkg/gui/controllers/tags_controller.go
  pkg/gui/extras_panel.go
  pkg/gui/gui.go
  pkg/gui/menu_panel.go
  pkg/gui/types/context.go
  pkg/gui/view_helpers.go
Labels: maintenance

#4404 More navigation keybindings for confirmation panel
  pkg/gui/extras_panel.go
  pkg/gui/global_handlers.go
  pkg/gui/keybindings.go
Labels: enhancement

#4452 Fix display of renamed files in tree view
  pkg/gui/presentation/files.go
  pkg/integration/tests/file/renamed_files.go
  pkg/integration/tests/test_list.go
Labels: ignore-for-release, blocks-release

#4431 Resolve non-inline merge conflicts
  pkg/commands/git_commands/working_tree.go
  pkg/commands/models/file.go
  pkg/gui/controllers/files_controller.go
  pkg/i18n/english.go
  pkg/integration/components/file_system.go
  pkg/integration/tests/conflicts/resolve_non_textual_conflicts.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4439 Bump the minimum required git version to 2.22
  .github/workflows/ci.yml
  pkg/app/app.go
  pkg/commands/git_commands/branch_loader.go
  pkg/commands/git_commands/branch_loader_test.go
  pkg/commands/git_commands/rebase.go
  pkg/commands/git_commands/rebase_test.go
  pkg/i18n/english.go
  pkg/integration/tests/interactive_rebase/drop_merge_commit.go
  pkg/integration/tests/interactive_rebase/edit_range_select_down_to_merge_outside_rebase.go
  pkg/integration/tests/interactive_rebase/edit_range_select_outside_rebase.go
  pkg/integration/tests/submodule/enter.go
  pkg/integration/tests/submodule/enter_nested.go
  pkg/integration/tests/submodule/reset.go
  scripts/run_integration_tests.sh
Labels: maintenance

#4456 Prefill the commit subject with the skipHook prefix when pressing `w`
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/integration/tests/commit/commit_wip_with_prefix.go
Labels: ignore-for-release

#4467 Show "(hooks disabled)" in title bar of commit message editor
  pkg/gui/context/commit_message_context.go
  pkg/gui/controllers/commit_message_controller.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/gui/editors.go
  pkg/i18n/english.go
Labels: enhancement, blocks-release

#4448 Add a command to select all commits of the current branch
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_pt.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/config/user_config.go
  pkg/gui/controllers/basic_commits_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/select_commits_of_current_branch.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#4459 fix: update vscode color to logo color
  pkg/gui/presentation/icons/file_icons.go
Labels: bug

#4480 Fix crash with drag selecting and staging
  pkg/gui/patch_exploring/state.go
Labels: bug, blocks-release

#4475 Escape special characters in filenames when git-ignoring files
  pkg/commands/git_commands/working_tree.go
  pkg/integration/tests/file/gitignore_special_characters.go
  pkg/integration/tests/test_list.go
Labels: bug

#4484 Skip date check when release worfklow is manually invoked
  .github/workflows/release.yml
Labels: maintenance

#4483 Fix truncation of branches when scrolling branches panel to the left
  pkg/gui/context/branches_context.go
  pkg/gui/controllers/list_controller.go
Labels: bug

#4441 Continue/abort a conflicted cherry-pick or revert
  pkg/commands/git.go
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/git_commands/patch.go
  pkg/commands/git_commands/status.go
  pkg/commands/models/working_tree_state.go
  pkg/commands/types/enums/enums.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/controllers/custom_patch_options_menu_action.go
  pkg/gui/controllers/global_controller.go
  pkg/gui/controllers/helpers/cherry_pick_helper.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/helpers/mode_helper.go
  pkg/gui/controllers/helpers/patch_building_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/status_controller.go
  pkg/gui/controllers/undo_controller.go
  pkg/gui/options_map.go
  pkg/gui/presentation/status.go
  pkg/gui/presentation/working_tree.go
  pkg/gui/types/common.go
  pkg/i18n/english.go
  pkg/integration/clients/injector/main.go
  pkg/integration/components/common.go
  pkg/integration/tests/branch/rebase.go
  pkg/integration/tests/branch/rebase_and_drop.go
  pkg/integration/tests/branch/rebase_conflicts_fix_build_errors.go
  pkg/integration/tests/cherry_pick/cherry_pick_conflicts.go
  pkg/integration/tests/commit/revert_with_conflict_single_commit.go
  pkg/integration/tests/commit/shared.go
  pkg/integration/tests/conflicts/resolve_externally.go
  pkg/integration/tests/conflicts/resolve_multiple_files.go
  pkg/integration/tests/conflicts/resolve_without_trailing_lf.go
  pkg/integration/tests/file/discard_all_dir_changes.go
  pkg/integration/tests/file/discard_various_changes.go
  pkg/integration/tests/file/discard_various_changes_range_select.go
  pkg/integration/tests/interactive_rebase/amend_commit_with_conflict.go
  pkg/integration/tests/interactive_rebase/rebase_with_commit_that_becomes_empty.go
  pkg/integration/tests/interactive_rebase/shared.go
  pkg/integration/tests/patch_building/move_to_earlier_commit_from_added_file.go
  pkg/integration/tests/patch_building/move_to_index_from_added_file_with_conflict.go
  pkg/integration/tests/patch_building/move_to_index_with_conflict.go
  pkg/integration/tests/sync/pull_merge_conflict.go
  pkg/integration/tests/sync/pull_rebase_conflict.go
  pkg/integration/tests/sync/pull_rebase_interactive_conflict.go
  pkg/integration/tests/sync/pull_rebase_interactive_conflict_drop.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4444 Allow reverting a range of commits
  pkg/commands/git_commands/commit.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/commit/revert_merge.go
  pkg/integration/tests/commit/revert_with_conflict_multiple_commits.go
  pkg/integration/tests/interactive_rebase/revert_during_rebase_when_stopped_on_edit.go
  pkg/integration/tests/interactive_rebase/revert_multiple_commits_in_interactive_rebase.go
Labels: enhancement

#4463 Section headers for rebase todos and actual commits
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/models/commit.go
  pkg/gui/context/list_context_trait.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/simple_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/presentation/commits.go
  pkg/gui/presentation/commits_test.go
  pkg/gui/types/context.go
  pkg/gui/view_helpers.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/rebase_and_drop.go
  pkg/integration/tests/cherry_pick/cherry_pick_during_rebase.go
  pkg/integration/tests/commit/amend_when_there_are_conflicts_and_amend.go
  pkg/integration/tests/commit/amend_when_there_are_conflicts_and_cancel.go
  pkg/integration/tests/commit/revert_with_conflict_multiple_commits.go
  pkg/integration/tests/commit/revert_with_conflict_single_commit.go
  pkg/integration/tests/commit/shared.go
  pkg/integration/tests/interactive_rebase/advanced_interactive_rebase.go
  pkg/integration/tests/interactive_rebase/amend_commit_with_conflict.go
  pkg/integration/tests/interactive_rebase/amend_head_commit_during_rebase.go
  pkg/integration/tests/interactive_rebase/amend_non_head_commit_during_rebase.go
  pkg/integration/tests/interactive_rebase/delete_update_ref_todo.go
  pkg/integration/tests/interactive_rebase/dont_show_branch_heads_for_todo_items.go
  pkg/integration/tests/interactive_rebase/drop_todo_commit_with_update_ref.go
  pkg/integration/tests/interactive_rebase/edit_and_auto_amend.go
  pkg/integration/tests/interactive_rebase/edit_first_commit.go
  pkg/integration/tests/interactive_rebase/edit_last_commit_of_stacked_branch.go
  pkg/integration/tests/interactive_rebase/edit_non_todo_commit_during_rebase.go
  pkg/integration/tests/interactive_rebase/edit_range_select_down_to_merge_outside_rebase.go
  pkg/integration/tests/interactive_rebase/edit_range_select_outside_rebase.go
  pkg/integration/tests/interactive_rebase/edit_the_confl_commit.go
  pkg/integration/tests/interactive_rebase/interactive_rebase_of_copied_branch.go
  pkg/integration/tests/interactive_rebase/interactive_rebase_with_conflict_for_edit_command.go
  pkg/integration/tests/interactive_rebase/mid_rebase_range_select.go
  pkg/integration/tests/interactive_rebase/move_in_rebase.go
  pkg/integration/tests/interactive_rebase/move_update_ref_todo.go
  pkg/integration/tests/interactive_rebase/pick_rescheduled.go
  pkg/integration/tests/interactive_rebase/quick_start.go
  pkg/integration/tests/interactive_rebase/quick_start_keep_selection.go
  pkg/integration/tests/interactive_rebase/quick_start_keep_selection_range.go
  pkg/integration/tests/interactive_rebase/rebase.go
  pkg/integration/tests/interactive_rebase/revert_during_rebase_when_stopped_on_edit.go
  pkg/integration/tests/interactive_rebase/revert_multiple_commits_in_interactive_rebase.go
  pkg/integration/tests/interactive_rebase/revert_single_commit_in_interactive_rebase.go
  pkg/integration/tests/interactive_rebase/reword_commit_with_editor_and_fail.go
  pkg/integration/tests/interactive_rebase/reword_you_are_here_commit.go
  pkg/integration/tests/interactive_rebase/reword_you_are_here_commit_with_editor.go
  pkg/integration/tests/interactive_rebase/shared.go
  pkg/integration/tests/interactive_rebase/show_exec_todos.go
  pkg/integration/tests/interactive_rebase/swap_in_rebase_with_conflict.go
  pkg/integration/tests/interactive_rebase/swap_in_rebase_with_conflict_and_edit.go
  pkg/integration/tests/interactive_rebase/view_files_of_todo_entries.go
  pkg/integration/tests/submodule/reset.go
  pkg/integration/tests/sync/pull_rebase_interactive_conflict.go
  pkg/integration/tests/sync/pull_rebase_interactive_conflict_drop.go
Labels: enhancement

#4429 Focus the main view
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_pt.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  go.mod
  go.sum
  pkg/commands/patch/patch.go
  pkg/config/user_config.go
  pkg/gui/context/base_context.go
  pkg/gui/context/context.go
  pkg/gui/context/list_renderer.go
  pkg/gui/context/main_context.go
  pkg/gui/context/setup.go
  pkg/gui/context/traits/list_cursor.go
  pkg/gui/controllers.go
  pkg/gui/controllers/attach.go
  pkg/gui/controllers/base_controller.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/main_view_controller.go
  pkg/gui/controllers/switch_to_focused_main_view_controller.go
  pkg/gui/controllers/vertical_scroll_controller.go
  pkg/gui/controllers/view_selection_controller.go
  pkg/gui/global_handlers.go
  pkg/gui/gui.go
  pkg/gui/gui_common.go
  pkg/gui/layout.go
  pkg/gui/mergeconflicts/state.go
  pkg/gui/types/common.go
  pkg/gui/types/context.go
  pkg/gui/view_helpers.go
  pkg/i18n/english.go
  pkg/integration/tests/patch_building/apply.go
  pkg/integration/tests/patch_building/apply_in_reverse.go
  pkg/integration/tests/patch_building/apply_in_reverse_with_conflict.go
  pkg/integration/tests/patch_building/move_range_to_index.go
  pkg/integration/tests/patch_building/move_to_index.go
  pkg/integration/tests/patch_building/move_to_index_partial.go
  pkg/integration/tests/patch_building/move_to_index_works_even_if_noprefix_is_set.go
  pkg/integration/tests/patch_building/remove_from_commit.go
  pkg/integration/tests/stash/stash_staged_partial_file.go
  pkg/integration/tests/ui/range_select.go
  pkg/tasks/tasks.go
  pkg/tasks/tasks_test.go
  pkg/utils/utils.go
  schema/config.json
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: enhancement

#4493 Auto-forward main branches after fetching
  docs/Config.md
  pkg/commands/git_commands/branch.go
  pkg/commands/oscommands/cmd_obj.go
  pkg/config/user_config.go
  pkg/config/user_config_validation.go
  pkg/gui/background.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/branches_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/sync/fetch_and_auto_forward_branches_all_branches.go
  pkg/integration/tests/sync/fetch_and_auto_forward_branches_none.go
  pkg/integration/tests/sync/fetch_and_auto_forward_branches_only_main_branches.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#3876 Add new command "Move commits to new branch"
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_pt.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/git_commands/branch.go
  pkg/config/user_config.go
  pkg/gui/controllers.go
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/branch/move_commits_to_new_branch_from_base_branch.go
  pkg/integration/tests/branch/move_commits_to_new_branch_from_main_branch.go
  pkg/integration/tests/branch/move_commits_to_new_branch_keep_stacked.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#4505 Allow changing diff context size and rename threshold when main view is focused
  pkg/gui/controllers/context_lines_controller.go
  pkg/gui/controllers/rename_similarity_threshold_controller.go
  pkg/integration/tests/diff/rename_similarity_threshold_change.go
  pkg/integration/tests/file/rename_similarity_threshold_change.go
Labels: ignore-for-release

#4501 Add Debian installation instructions alongside Ubuntu
  README.md
Labels: docs

#4515 Allow closing issues via github actions
  .github/workflows/close-issues.yml
Labels: maintenance

#4518 Fix race condition when starting several command tasks in quick succession
  pkg/tasks/tasks.go
Labels: ignore-for-release

#4506 Fix nvim-remote commands for fish shell
  pkg/commands/git_commands/file.go
  pkg/config/editor_presets.go
  pkg/config/editor_presets_test.go
Labels: bug

#4522 Disallow creating custom patches when the diff context size is 0
  pkg/gui/controllers/commits_files_controller.go
  pkg/i18n/english.go
Labels: bug

#4520 Remove double space between rebase todo and author columns
  pkg/gui/presentation/commits.go
  pkg/gui/presentation/commits_test.go
  pkg/integration/tests/cherry_pick/cherry_pick_during_rebase.go
  pkg/integration/tests/interactive_rebase/edit_range_select_down_to_merge_outside_rebase.go
  pkg/integration/tests/interactive_rebase/edit_range_select_outside_rebase.go
Labels: bug

#4488 fix wording of random tip
  pkg/gui/command_log_panel.go
Labels: docs

#4498 Reduce memory consumption of graph (pipe sets)
  go.mod
  go.sum
  pkg/app/daemon/rebase.go
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/git_commands/patch.go
  pkg/commands/git_commands/rebase.go
  pkg/commands/git_commands/rebase_test.go
  pkg/commands/git_commands/reflog_commit_loader.go
  pkg/commands/git_commands/reflog_commit_loader_test.go
  pkg/commands/models/commit.go
  pkg/config/app_config_test.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/controllers/bisect_controller.go
  pkg/gui/controllers/custom_patch_options_menu_action.go
  pkg/gui/controllers/helpers/cherry_pick_helper.go
  pkg/gui/controllers/helpers/diff_helper.go
  pkg/gui/controllers/helpers/fixup_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/helpers/sub_commits_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/reflog_commits_controller.go
  pkg/gui/controllers/undo_controller.go
  pkg/gui/gui.go
  pkg/gui/modes/cherrypicking/cherry_picking.go
  pkg/gui/presentation/authors/authors.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/commits.go
  pkg/gui/presentation/commits_test.go
  pkg/gui/presentation/files_test.go
  pkg/gui/presentation/graph/cell.go
  pkg/gui/presentation/graph/graph.go
  pkg/gui/presentation/graph/graph_test.go
  pkg/gui/presentation/icons/git_icons.go
  pkg/gui/presentation/reflog_commits.go
  pkg/gui/services/custom_commands/session_state_loader.go
  pkg/gui/types/common.go
  pkg/utils/color.go
  pkg/utils/formatting_test.go
  pkg/utils/string_pool.go
  vendor/github.com/stefanhaller/git-todo-parser/todo/parse.go
  vendor/github.com/stefanhaller/git-todo-parser/todo/todo.go
  vendor/modules.txt
Labels: enhancement
