Repository jesseduffield/lazygit, pull requests merged in 2025-08, with the labels that each got.

#4789 Fix commit hash colors when filtering by path or aythor
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/git_commands/main_branches.go
  pkg/commands/models/ref.go
  pkg/gui/context/branches_context.go
  pkg/gui/context/commit_files_context.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/reflog_commits_context.go
  pkg/gui/context/remote_branches_context.go
  pkg/gui/context/stash_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/context/tags_context.go
  pkg/gui/controllers/helpers/diff_helper.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/controllers/helpers/sub_commits_helper.go
  pkg/gui/controllers/switch_to_diff_files_controller.go
  pkg/gui/controllers/switch_to_sub_commits_controller.go
  pkg/gui/filetree/commit_file_tree_view_model.go
  pkg/gui/types/ref_range.go
Labels: bug

#4784 Improve temp dir handling
  .gitignore
  pkg/app/daemon/daemon.go
  pkg/app/entry_point.go
Labels: bug

#4780 Enable hunk staging mode by default
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/app/entry_point.go
  pkg/config/app_config.go
  pkg/config/user_config.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/patch_building_helper.go
  pkg/gui/controllers/options_menu_action.go
  pkg/gui/controllers/patch_explorer_controller.go
  pkg/gui/options_map.go
  pkg/gui/types/keybindings.go
  pkg/i18n/english.go
  pkg/integration/tests/commit/stage_range_of_lines.go
  pkg/integration/tests/demo/custom_patch.go
  pkg/integration/tests/patch_building/move_to_index_partial.go
  pkg/integration/tests/patch_building/specific_selection.go
  pkg/integration/tests/staging/diff_context_change.go
  pkg/integration/tests/staging/discard_all_changes.go
  pkg/integration/tests/staging/stage_hunks.go
  pkg/integration/tests/staging/stage_lines.go
  pkg/integration/tests/staging/stage_ranges.go
  pkg/integration/tests/stash/stash_staged_partial_file.go
  pkg/integration/tests/ui/range_select.go
  schema/config.json
Labels: enhancement

#4792 Update Fedora section of the README.md file
  README.md
Labels: docs

#4796 Fix temp dir permission problem on multi-user machines
  pkg/app/entry_point.go
Labels: bug

#4806 Update `CONTRIBUTING.md` to clarify translation contribution process
  CONTRIBUTING.md
Labels: docs

#4803 Fix delay with flicking through files or commits when git diff is very slow
  pkg/commands/oscommands/os.go
  pkg/commands/oscommands/os_default_platform.go
  pkg/commands/oscommands/os_windows.go
  pkg/tasks/tasks.go
Labels: bug

#4820 Add installation with gah
  README.md
Labels: docs

#4836 Use external diff command in stashes panel
  pkg/commands/git_commands/stash.go
  pkg/commands/git_commands/stash_test.go
Labels: bug

#4837 Remove the git.paging.useConfig option
  docs/Config.md
  docs/Custom_Pagers.md
  pkg/commands/git_commands/config.go
  pkg/config/user_config.go
  pkg/i18n/english.go
  schema/config.json
Labels: bug

#4832 Add a user config for using git's external diff command for paging
  docs/Config.md
  docs/Custom_Pagers.md
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
  pkg/commands/git_commands/diff.go
  pkg/commands/git_commands/stash.go
  pkg/commands/git_commands/stash_test.go
  pkg/commands/git_commands/working_tree.go
  pkg/config/user_config.go
  schema/config.json
Labels: enhancement

#4850 Log the hash of dropped stashes
  pkg/commands/git_commands/stash_loader.go
  pkg/commands/git_commands/stash_loader_test.go
  pkg/commands/models/stash_entry.go
  pkg/gui/controllers/stash_controller.go
  pkg/i18n/english.go
Labels: enhancement
