Repository jesseduffield/lazygit, pull requests merged in 2025-05, with the labels that each got.

#4525 Clean up the configuration of where a custom command's output goes
  docs/Custom_Command_Keybindings.md
  pkg/commands/git_cmd_obj_builder.go
  pkg/commands/git_cmd_obj_runner.go
  pkg/commands/git_commands/branch.go
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_loader.go
  pkg/commands/git_commands/diff.go
  pkg/commands/git_commands/flow.go
  pkg/commands/git_commands/rebase.go
  pkg/commands/git_commands/rebase_test.go
  pkg/commands/git_commands/stash.go
  pkg/commands/git_commands/submodule.go
  pkg/commands/git_commands/sync.go
  pkg/commands/git_commands/sync_test.go
  pkg/commands/git_commands/tag.go
  pkg/commands/git_commands/working_tree.go
  pkg/commands/oscommands/cmd_obj.go
  pkg/commands/oscommands/cmd_obj_builder.go
  pkg/commands/oscommands/cmd_obj_runner.go
  pkg/commands/oscommands/cmd_obj_runner_default.go
  pkg/commands/oscommands/cmd_obj_runner_win.go
  pkg/commands/oscommands/fake_cmd_obj_runner.go
  pkg/commands/oscommands/os.go
  pkg/config/app_config.go
  pkg/config/app_config_test.go
  pkg/config/user_config.go
  pkg/config/user_config_validation.go
  pkg/config/user_config_validation_test.go
  pkg/gui/controllers/helpers/gpg_helper.go
  pkg/gui/controllers/helpers/tags_helper.go
  pkg/gui/gui.go
  pkg/gui/gui_common.go
  pkg/gui/services/custom_commands/handler_creator.go
  pkg/gui/types/common.go
  pkg/i18n/english.go
  pkg/integration/tests/custom_commands/show_output_in_panel.go
  pkg/utils/yaml_utils/yaml_utils.go
  pkg/utils/yaml_utils/yaml_utils_test.go
  schema/config.json
Labels: enhancement

#4538 Clean up utils package
  pkg/commands/git_commands/commit_loader_test.go
  pkg/commands/git_commands/deps_test.go
  pkg/commands/git_commands/reflog_commit_loader_test.go
  pkg/commands/git_commands/stash_loader_test.go
  pkg/commands/git_commands/tag_loader_test.go
  pkg/commands/oscommands/dummies.go
  pkg/common/dummies.go
  pkg/gui/dummies.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/branches_test.go
  pkg/gui/presentation/commits_test.go
  pkg/gui/presentation/loader.go
  pkg/gui/presentation/remotes.go
  pkg/gui/presentation/tags.go
  pkg/gui/services/custom_commands/menu_generator_test.go
  pkg/gui/status/status_manager.go
  pkg/utils/dummies.go
  pkg/utils/utils.go
Labels: maintenance

#4545 reword documentation for git.autoForwardBranches
  docs/Config.md
  pkg/config/user_config.go
  schema/config.json
Labels: docs

#4544 Make '>' first jump to the beginning of the branch, and only then to the first commit
  pkg/gui/context/list_context_trait.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/controllers/list_controller.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/types/context.go
Labels: enhancement

#4532 Add an alternate keybinding (default <c-s>) for ConfirmInEditor
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/controllers/commit_description_controller.go
  pkg/i18n/english.go
  schema/config.json
Labels: enhancement

#4558 Clear preserved commit message when entering CommitEditorPanel
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/helpers/tags_helper.go
  pkg/gui/controllers/helpers/working_tree_helper.go
Labels: bug

#4574 Split behavior of rendering allBranchesLogCmd and switching to next cmd
  pkg/commands/git_commands/branch.go
  pkg/gui/controllers/status_controller.go
  pkg/integration/tests/status/log_cmd_status_panel_all_branches_log.go
  pkg/integration/tests/test_list.go
Labels: bug

#4565 Fix possible crash with auto-forwarding branches
  pkg/gui/controllers/helpers/branches_helper.go
Labels: bug

#4548 Print migration changes to the console when migrating config file
  go.mod
  go.sum
  pkg/config/app_config.go
  pkg/config/app_config_test.go
  pkg/utils/yaml_utils/yaml_utils.go
  pkg/utils/yaml_utils/yaml_utils_test.go
  vendor/github.com/jesseduffield/generics/maps/maps.go
  vendor/github.com/jesseduffield/generics/orderedset/orderedset.go
  vendor/github.com/jesseduffield/generics/set/set.go
  vendor/modules.txt
Labels: enhancement, blocks-release

#4573 Fix main view occasionally scrolling to the top on its own when focused
  pkg/gui/view_helpers.go
Labels: bug

#4554 Fix home and end keys in prompts
  go.mod
  go.sum
  pkg/gui/global_handlers.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: bug

#4567 Fix crash when clicking in the status view
  pkg/gui/context.go
  pkg/gui/controllers/context_lines_controller.go
  pkg/gui/controllers/main_view_controller.go
  pkg/gui/controllers/rename_similarity_threshold_controller.go
  pkg/gui/controllers/switch_to_focused_main_view_controller.go
  pkg/gui/types/context.go
  pkg/gui/view_helpers.go
Labels: bug

#4586 Fix lazygit's UI becoming unresponsive when a background fetch asks for a passphrase
  pkg/commands/oscommands/cmd_obj.go
Labels: bug

#4588 Kill background fetch when it requests a passphrase
  pkg/commands/oscommands/cmd_obj_runner.go
  pkg/commands/oscommands/cmd_obj_runner_test.go
Labels: bug

#4597 Fix branch selection jumping back on background fetch
  pkg/gui/controllers/helpers/refresh_helper.go
Labels: bug

#4604 Use branchPrefix when moving commits to new branch
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/integration/tests/branch/move_commits_to_new_branch_keep_stacked.go
Labels: enhancement

#4613 Replace literal with ConfigFilename constant
  pkg/config/app_config.go
Labels: maintenance
