Repository jesseduffield/lazygit, pull requests merged in 2025-09, with the labels that each got.

#4860 Make it possible to rebind the Confirm keybinding
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_pt.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/cheatsheet/generate.go
  pkg/config/user_config.go
  pkg/gui/context/context.go
  pkg/gui/context/prompt_context.go
  pkg/gui/context/setup.go
  pkg/gui/controllers.go
  pkg/gui/controllers/confirmation_controller.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/controllers/menu_controller.go
  pkg/gui/controllers/prompt_controller.go
  pkg/gui/controllers/search_prompt_controller.go
  pkg/gui/controllers/suggestions_controller.go
  pkg/gui/controllers/worktrees_controller.go
  pkg/gui/global_handlers.go
  pkg/gui/gui.go
  pkg/gui/keybindings.go
  pkg/gui/menu_panel.go
  pkg/gui/types/views.go
  pkg/gui/views.go
  pkg/i18n/english.go
  pkg/integration/components/commit_description_panel_driver.go
  pkg/integration/components/menu_driver.go
  pkg/integration/components/popup.go
  pkg/integration/components/prompt_driver.go
  pkg/integration/components/views.go
  schema/config.json
Labels: bug

#4795 README.md: Update Sponsors
  README.md
Labels: ignore-for-release

#4895 Fix staging when using the new useExternalDiffGitConfig config
  pkg/commands/git_commands/working_tree.go
Labels: bug

#4867 Fix MoveCommitsToNewBranch description typo
  pkg/i18n/english.go
Labels: docs

#4896 Don't log the git rev-list command that we use for IsBranchMerged
  pkg/commands/git_commands/branch.go
Labels: bug

#4878 Hide the cursor when the password prompt is showing
  pkg/gui/context.go
Labels: bug
