Repository jesseduffield/lazygit, pull requests merged in 2025-02, with the labels that each got.

#4232 Fix tag being truncated when copying to clipboard
  pkg/gui/keybindings.go
  pkg/integration/tests/tag/copy_to_clipboard.go
Labels: bug

#4235 Disable staging and unstaging lines or hunks when the diff context size is 0
  pkg/gui/controllers/staging_controller.go
  pkg/i18n/english.go
Labels: bug

#4213 Fix incorrect stash diff after rename
  pkg/gui/controllers/stash_controller.go
  pkg/integration/tests/stash/rename.go
Labels: bug

#4226 Allow user to filter the files view to only show untracked files
  pkg/commands/git_commands/file_loader.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/filetree/file_tree.go
  pkg/i18n/english.go
  pkg/integration/tests/filter_and_search/filter_by_file_status.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4230 Show files filter status
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/conflicts/filter.go
  pkg/integration/tests/filter_and_search/filter_by_file_status.go
Labels: enhancement

#4191 Preserve pending commit message when closing/re-opening
  pkg/gui/context/commit_message_context.go
  pkg/gui/controllers/helpers/commits_helper.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/integration/components/commit_description_panel_driver.go
  pkg/integration/components/commit_message_panel_driver.go
  pkg/integration/components/view_driver.go
  pkg/integration/tests/commit/preserve_commit_message.go
Labels: enhancement

#4195 Fix possible crash when deleting a branch while filtering is active
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/integration/tests/branch/delete_while_filtering.go
  pkg/integration/tests/test_list.go
Labels: bug

#4242 Improve contrast of highlighted search results
  go.mod
  go.sum
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: enhancement

#4238 Swap position of checkout-commit and checkout-branch menu items
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/integration/tests/commit/checkout.go
Labels: enhancement, blocks-release

#4234 Fix pasting multi-line text into commit message panel
  go.mod
  go.sum
  pkg/gui/controllers/commit_description_controller.go
  pkg/gui/controllers/commit_message_controller.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/github.com/jesseduffield/gocui/tcell_driver.go
  vendor/modules.txt
Labels: bug

#4255 Fix json schema for context of CustomCommand
  pkg/config/user_config.go
  schema/config.json
Labels: bug

#4250 Update translations; includes a new Portuguese translation
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_pt.md
  docs/keybindings/Keybindings_zh-CN.md
  pkg/i18n/translations/README.md
  pkg/i18n/translations/ko.json
  pkg/i18n/translations/pt.json
  pkg/i18n/translations/zh-CN.json
  pkg/i18n/translations/zh-TW.json
  scripts/update_language_files.sh
Labels: i18n

#4231 Don't try killing processes if we already know the command finished + reduce error logging noise on Windows
  pkg/tasks/tasks.go
Labels: bug, blocks-release

#4265 Fix auto-release workflow
  .github/workflows/release.yml
Labels: maintenance

#4274 Add option to copy commit body
  pkg/gui/controllers/basic_commits_controller.go
  pkg/i18n/english.go
  pkg/integration/components/shell.go
  pkg/integration/tests/commit/copy_message_body_to_clipboard.go
  pkg/integration/tests/commit/disable_copy_commit_message_body.go
  pkg/integration/tests/commit/paste_commit_message.go
  pkg/integration/tests/commit/paste_commit_message_over_existing.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4282 Fix documentation of gui.showFileTree config
  docs/Config.md
  pkg/config/user_config.go
  schema/config.json
Labels: docs

#4271 Add a "Copy to clipboard" menu to the Commit Files panel
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_pt.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/gui/controllers/commits_files_controller.go
  pkg/integration/tests/commit/copy_author_to_clipboard.go
  pkg/integration/tests/commit/copy_tag_to_clipboard.go
  pkg/integration/tests/commit/paste_commit_message.go
  pkg/integration/tests/commit/paste_commit_message_over_existing.go
  pkg/integration/tests/diff/copy_to_clipboard.go
  pkg/integration/tests/file/copy_menu.go
  pkg/integration/tests/misc/copy_to_clipboard.go
  pkg/integration/tests/tag/copy_to_clipboard.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4291 Add gui.tabWidth config
  docs/Config.md
  go.mod
  go.sum
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/patch_exploring/state.go
  pkg/gui/views.go
  pkg/utils/lines.go
  pkg/utils/lines_test.go
  schema/config.json
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: enhancement

#4275 Validate user config keybindings
  docs/keybindings/Custom_Keybindings.md
  pkg/config/keynames.go
  pkg/config/user_config_validation.go
  pkg/config/user_config_validation_test.go
  pkg/gui/keybindings/keybindings.go
Labels: bug

#3932 Add --include-untracked flag to stash show command
  pkg/commands/git_commands/stash.go
  pkg/commands/git_commands/stash_test.go
Labels: bug

#4305 Update README.md
  README.md
Labels: ignore-for-release

#4268 Fix race condition with reselecting the focused branch and rendering
  pkg/gui/controllers/helpers/refresh_helper.go
Labels: maintenance

#4308 Fix auto-release schedule
  .github/workflows/release.yml
Labels: maintenance

#4284 fix: Disable global keybinds when confirmation is active
  pkg/gui/controllers/global_controller.go
  pkg/gui/controllers/jump_to_side_window_controller.go
  pkg/gui/gui.go
  pkg/gui/keybindings.go
  pkg/i18n/english.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/ui/double_popup.go
Labels: bug

#4312 Use indentation of 2 when rewriting auto-migrated config file
  pkg/utils/yaml_utils/yaml_utils.go
  pkg/utils/yaml_utils/yaml_utils_test.go
Labels: ignore-for-release

#4311 Don't rewrite config file unnecessarily when it contains commitPrefixes
  pkg/config/app_config.go
  pkg/config/app_config_test.go
Labels: bug

#4309 Use refs in jsonschema
  docs/Config.md
  go.mod
  go.sum
  pkg/config/user_config.go
  pkg/jsonschema/generate.go
  pkg/jsonschema/generate_config_docs.go
  pkg/jsonschema/generator.go
  schema/config.json
  vendor/github.com/iancoleman/orderedmap/LICENSE
  vendor/github.com/iancoleman/orderedmap/orderedmap.go
  vendor/github.com/iancoleman/orderedmap/readme.md
  vendor/modules.txt
Labels: maintenance

#4307 Improve release workflow
  .github/workflows/cd.yml
  .github/workflows/release.yml
Labels: maintenance

#4287 Change side panel width calculation to work for larger numbers
  pkg/gui/controllers/helpers/window_arrangement_helper.go
  pkg/gui/controllers/helpers/window_arrangement_helper_test.go
Labels: bug

#4296 Improve the error message when users have gpg signing turned on
  pkg/i18n/english.go
Labels: docs

#4313 Skip post-checkout hook when discarding changes
  pkg/commands/git_commands/rebase_test.go
  pkg/commands/git_commands/working_tree.go
  pkg/commands/git_commands/working_tree_test.go
Labels: enhancement

#4319 Filter out dev comments from schema
  .vscode/launch.json
  pkg/jsonschema/generate.go
  pkg/jsonschema/generate_config_docs.go
  schema/config.json
Labels: maintenance, blocks-release

#4322 Fix release script
  .github/workflows/release.yml
Labels: maintenance

#4323 Fix release script once again
  .github/workflows/release.yml
Labels: maintenance

#4318 Refactor migrations to only marshall yaml twice
  pkg/config/app_config.go
  pkg/config/app_config_test.go
  pkg/utils/yaml_utils/yaml_utils.go
  pkg/utils/yaml_utils/yaml_utils_test.go
Labels: maintenance

#4324 Custom commands submenus
  docs/Custom_Command_Keybindings.md
  pkg/config/user_config.go
  pkg/config/user_config_validation.go
  pkg/config/user_config_validation_test.go
  pkg/gui/services/custom_commands/client.go
  pkg/gui/services/custom_commands/handler_creator.go
  pkg/gui/services/custom_commands/keybinding_creator.go
  pkg/gui/services/custom_commands/models.go
  pkg/i18n/english.go
  pkg/integration/tests/custom_commands/check_for_conflicts.go
  pkg/integration/tests/custom_commands/custom_commands_submenu.go
  pkg/integration/tests/custom_commands/global_context.go
  pkg/integration/tests/custom_commands/multiple_contexts.go
  pkg/integration/tests/custom_commands/show_output_in_panel.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement
