Repository jesseduffield/lazygit, pull requests merged in 2025-03, with the labels that each got.

#4352 Fix linter warnings
  pkg/commands/git_commands/deps_test.go
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/controllers/bisect_controller.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/git_flow_controller.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/controllers/menu_controller.go
  pkg/gui/controllers/reflog_commits_controller.go
  pkg/gui/controllers/remote_branches_controller.go
  pkg/gui/controllers/remotes_controller.go
  pkg/gui/controllers/stash_controller.go
  pkg/gui/controllers/sub_commits_controller.go
  pkg/gui/controllers/submodules_controller.go
  pkg/gui/controllers/suggestions_controller.go
  pkg/gui/controllers/switch_to_sub_commits_controller.go
  pkg/gui/controllers/tags_controller.go
  pkg/gui/controllers/worktree_options_controller.go
  pkg/gui/controllers/worktrees_controller.go
Labels: maintenance

#4350 Support fish when running shell command
  pkg/commands/oscommands/os_default_platform.go
Labels: enhancement

#4343 Use a waiting status for rewording a non-head commit
  pkg/gui/controllers/local_commits_controller.go
  pkg/i18n/english.go
Labels: bug

#4359 Fix layout of options view for non-english languages
  pkg/gui/options_map.go
Labels: bug

#4364 Fix release schedule again
  .github/workflows/release.yml
Labels: maintenance

#4360 Add acme editor preset
  docs/Config.md
  pkg/config/editor_presets.go
  pkg/config/user_config.go
  schema/config.json
Labels: enhancement

#4377 Update to go 1.24
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  go.mod
  pkg/cheatsheet/generate.go
  pkg/commands/git_commands/branch_loader.go
  pkg/commands/git_commands/remote_loader.go
  pkg/gui/controllers/helpers/window_arrangement_helper_test.go
  pkg/gui/filetree/node.go
  pkg/gui/presentation/graph/graph.go
Labels: maintenance

#4382 Add an integration test for a config with a negative refspec
  pkg/integration/tests/config/negative_refspec.go
  pkg/integration/tests/test_list.go
Labels: maintenance

#4336 URL encode gitlab brackets to make consistent with branch names
  pkg/commands/hosting_service/definitions.go
  pkg/commands/hosting_service/hosting_service_test.go
Labels: bug

#4381 Fix commitPrefix setting with empty pattern
  docs/Config.md
  pkg/gui/controllers/helpers/working_tree_helper.go
Labels: bug

#4386 Commit only tracked files in tracked filter view
  pkg/commands/git_commands/working_tree.go
  pkg/commands/git_commands/working_tree_test.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/gui/filetree/file_tree.go
  pkg/integration/tests/filter_and_search/filter_by_file_status.go
  pkg/integration/tests/filter_and_search/staging_folder_stages_only_tracked_files_in_tracked_only_filter.go
  pkg/integration/tests/test_list.go
Labels: bug

#4407 Revert #4313 (Skip post-checkout hook when discarding changes)
  pkg/commands/git_commands/rebase_test.go
  pkg/commands/git_commands/working_tree.go
  pkg/commands/git_commands/working_tree_test.go
Labels: bug

#4376 Drop the git config cache when getting focus
  pkg/commands/git_commands/config.go
  pkg/commands/git_config/cached_git_config.go
  pkg/commands/git_config/fake_git_config.go
  pkg/gui/context/list_renderer_test.go
  pkg/gui/gui.go
Labels: enhancement

#4341 Add a "Content of selected file" entry to the copy menu for commit files
  pkg/commands/git_commands/commit.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/diff/copy_to_clipboard.go
Labels: enhancement

#4393 Specify a go release minor version
  go.mod
Labels: maintenance

#4259 [FEAT] Add Recursive Bulk Initialize and Update for Submodules
  pkg/commands/git_commands/submodule.go
  pkg/gui/controllers/submodules_controller.go
  pkg/i18n/english.go
Labels: enhancement

#4374 Commit without pre-commit hooks action is independent on prefix
  pkg/commands/git_commands/commit.go
  pkg/commands/git_commands/commit_test.go
  pkg/commands/git_commands/patch.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/commit/commit_skip_hooks.go
  pkg/integration/tests/commit/commit_switch_to_editor_skip_hooks.go
  pkg/integration/tests/commit/commit_wip_with_prefix.go
  pkg/integration/tests/commit/fail_hooks_then_commit_no_hooks.go
  pkg/integration/tests/commit/shared.go
  pkg/integration/tests/commit/staged_without_hooks.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4413 Include empty arrays and maps in config docs
  docs/Config.md
  pkg/config/user_config.go
  pkg/jsonschema/generate_config_docs.go
  schema/config.json
Labels: docs

#4416 Filter out deprecated user config fields from generated Config.md
  docs/Config.md
  pkg/config/user_config.go
  pkg/jsonschema/generate_config_docs.go
Labels: docs

#4395 Let users define custom icons and color for files on the config file
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/context/commit_files_context.go
  pkg/gui/context/working_tree_context.go
  pkg/gui/presentation/files.go
  pkg/gui/presentation/files_test.go
  pkg/gui/presentation/icons/file_icons.go
  schema/config.json
Labels: enhancement

#4423 Fix checking out a file from a range selection of commits
  pkg/gui/controllers/commits_files_controller.go
  pkg/integration/tests/commit/checkout_file_from_commit.go
  pkg/integration/tests/commit/checkout_file_from_range_selection_of_commits.go
  pkg/integration/tests/test_list.go
Labels: bug

#4410 Add "Absolute path" item to the file view's copy menu
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/diff/copy_to_clipboard.go
  pkg/integration/tests/file/copy_menu.go
Labels: enhancement

#4432 Fix flaky integration test
  pkg/gui/main_panels.go
  pkg/gui/pty.go
Labels: maintenance
