Repository jesseduffield/lazygit, pull requests merged in 2025-10, with the labels that each got.

#4929 Give better visual feedback when checking out the previous branch
  pkg/commands/git_commands/branch.go
  pkg/gui/controllers/branches_controller.go
  pkg/gui/controllers/helpers/refs_helper.go
Labels: enhancement

#4844 Update go to 1.25
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  go.mod
  scripts/golangci-lint-shim.sh
Labels: maintenance

#4934 Update Merge conflicts menu keybinding to use p instead of k
  pkg/gui/controllers/files_controller.go
Labels: bug

#4920 Fix normalisedSelectedNodes function
  pkg/gui/controllers/files_controller.go
Labels: maintenance
