Repository jesseduffield/lazygit, pull requests merged in 2025-06, with the labels that each got.

#4640 Add option to disable warning when amending last commit
  docs/Config.md
  pkg/config/app_config_test.go
  pkg/config/user_config.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/local_commits_controller.go
  schema/config.json
Labels: enhancement

#4644 Add bold style for border
  docs/Config.md
  pkg/config/app_config_test.go
  pkg/config/user_config.go
  pkg/gui/views.go
  schema/config.json
Labels: enhancement

#4632 Instantiate mutexes by value
  pkg/commands/git_commands/main_branches.go
  pkg/gui/context/filtered_list.go
  pkg/gui/context/merge_conflicts_context.go
  pkg/gui/context/patch_explorer_context.go
  pkg/gui/controllers/helpers/inline_status_helper.go
  pkg/gui/gui.go
  pkg/gui/gui_common.go
  pkg/gui/types/common.go
Labels: maintenance

#4653 Fix DEFAULT_REMOTE_ICON character code
  pkg/gui/presentation/icons/git_icons.go
Labels: bug

#4646 Add credential prompts for PKCS11-based SSH keys
  pkg/commands/oscommands/cmd_obj_runner.go
  pkg/commands/oscommands/cmd_obj_runner_test.go
Labels: enhancement

#4660 Show GPG error before entering commit editor when rewording non-latest commits
  pkg/commands/git_commands/rebase.go
  pkg/gui/controllers/local_commits_controller.go
Labels: bug

#4669 Fix branch head icon appearing at head commit when a remote or tag exists with the same name as the current branch
  pkg/commands/git_commands/branch.go
  pkg/gui/controllers/helpers/refresh_helper.go
  pkg/integration/tests/commit/do_not_show_branch_marker_for_head_commit.go
  pkg/integration/tests/test_list.go
Labels: bug
