Repository jesseduffield/lazygit, pull requests merged in 2025-01, with the labels that each got.

#4135 docs: Stylize and correct the NixOS section in README.md
  README.md
Labels: docs

#4137 Bump kill package
  go.mod
  go.sum
  vendor/github.com/jesseduffield/kill/kill_windows.go
  vendor/modules.txt
Labels: bug

#4117 Allow to switch branches in Commit View (#4115)
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/commit/checkout.go
  pkg/integration/tests/reflog/checkout.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#3954 Allow on prem Azure DevOps Server pull request
  pkg/commands/hosting_service/definitions.go
  pkg/commands/hosting_service/hosting_service_test.go
Labels: enhancement

#4140 Update chinese translation for pull requests
  docs/keybindings/Keybindings_zh-CN.md
  pkg/i18n/translations/zh-CN.json
Labels: docs

#4029 enhancement: Use HEX colors on file icons instead of C256 colors
  pkg/gui/presentation/files.go
  pkg/gui/presentation/icons/file_icons.go
  pkg/gui/presentation/icons/icons.go
Labels: maintenance

#4138 Set repology table to 3 columns
  README.md
Labels: docs

#3597 Update instructions for using OSC52 with tmux
  docs/Config.md
Labels: docs

#4103 Add screen-mode command line argument
  pkg/app/entry_point.go
  pkg/app/types/types.go
  pkg/gui/gui.go
Labels: enhancement

#4141 Default to half-screen mode when opening with certain CLI args
  pkg/gui/gui.go
  pkg/integration/tests/demo/bisect.go
  pkg/integration/tests/demo/commit_graph.go
  pkg/integration/tests/demo/interactive_rebase.go
  pkg/integration/tests/demo/nuke_working_tree.go
Labels: enhancement

#3846 Update docs to describe use of custom commands without keybindings
  docs/Custom_Command_Keybindings.md
Labels: docs

#4051 Add worktree option to fast forwarding operation
  pkg/commands/git_commands/git_command_builder.go
  pkg/commands/git_commands/sync.go
  pkg/gui/controllers/branches_controller.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/worktree/fast_forward_worktree_branch_should_not_pollute_current_worktree.go
Labels: bug

#4107 chore: use errors.New to replace fmt.Errorf with no parameters
  pkg/commands/git_commands/working_tree_test.go
Labels: maintenance

#3920 Fix typos
  docs/dev/Busy.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/commands/oscommands/os_test.go
  pkg/gui/context/list_context_trait.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/refs_helper.go
  pkg/gui/controllers/helpers/window_arrangement_helper_test.go
  pkg/gui/controllers/helpers/working_tree_helper.go
  pkg/gui/controllers/local_commits_controller.go
  pkg/gui/patch_exploring/state.go
  pkg/i18n/english.go
  pkg/integration/clients/go_test.go
  pkg/integration/components/env.go
  pkg/integration/tests/demo/shared.go
  pkg/integration/tests/sync/fetch_prune.go
  pkg/integration/tests/test_list_generator.go
  pkg/integration/tests/ui/accordion.go
  pkg/integration/tests/worktree/bare_repo_worktree_config.go
Labels: maintenance

#3094 documentation - describe os.openLink
  docs/Config.md
Labels: docs

#4114 Clarify commit message prefix mechanics
  docs/Config.md
Labels: docs

#4145 Tweak file icons
  pkg/gui/presentation/icons/file_icons.go
Labels: maintenance

#4143 Don't show keybindings option in bottom line when panel is open
  pkg/gui/controllers/global_controller.go
  pkg/gui/controllers/options_menu_action.go
  pkg/gui/keybindings.go
Labels: bug

#4136 Show the alt-enter keybinding at bottom of commit description view
  pkg/gui/controllers/commit_description_controller.go
  pkg/gui/controllers/commit_message_controller.go
  pkg/i18n/english.go
Labels: enhancement

#4151 Fix reset/rebase to upstream
  pkg/gui/controllers/branches_controller.go
  pkg/integration/components/shell.go
  pkg/integration/tests/branch/rebase_to_upstream.go
  pkg/integration/tests/branch/reset_to_upstream.go
Labels: bug

#4152 Avoid blank line at end of view
  go.mod
  go.sum
  pkg/integration/tests/patch_building/move_to_index_part_of_adjacent_added_lines.go
  pkg/integration/tests/stash/stash_staged_partial_file.go
  pkg/utils/lines.go
  pkg/utils/lines_test.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: bug

#4119 Adjust line number for working copy when editing a line
  go.mod
  go.sum
  pkg/commands/git_commands/diff.go
  pkg/commands/patch/patch.go
  pkg/commands/patch/patch_test.go
  pkg/gui/context/branches_context.go
  pkg/gui/context/commit_files_context.go
  pkg/gui/context/local_commits_context.go
  pkg/gui/context/reflog_commits_context.go
  pkg/gui/context/remote_branches_context.go
  pkg/gui/context/remotes_context.go
  pkg/gui/context/stash_context.go
  pkg/gui/context/sub_commits_context.go
  pkg/gui/context/tags_context.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/diff_helper.go
  pkg/gui/controllers/patch_building_controller.go
  pkg/gui/controllers/staging_controller.go
  pkg/gui/gui.go
  pkg/gui/types/context.go
  pkg/integration/tests/patch_building/edit_line_in_patch_building_panel.go
  pkg/integration/tests/test_list.go
  vendor/github.com/jesseduffield/gocui/gui.go
  vendor/modules.txt
Labels: bug, blocks-release

#4158 Add number of commits to cherry-pick confirmation prompt
  pkg/gui/controllers/helpers/cherry_pick_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/cherry_pick/cherry_pick.go
  pkg/integration/tests/cherry_pick/cherry_pick_conflicts.go
  pkg/integration/tests/cherry_pick/cherry_pick_during_rebase.go
  pkg/integration/tests/cherry_pick/cherry_pick_range.go
  pkg/integration/tests/demo/cherry_pick.go
  pkg/integration/tests/reflog/cherry_pick.go
Labels: enhancement

#4156 Fix `micro` editor preset
  pkg/config/editor_presets.go
Labels: bug

#4159 Use interactive shell for running shell commands only if shell is bash or zsh
  pkg/commands/oscommands/os_default_platform.go
Labels: bug, blocks-release

#4142 Standardise on 'screen mode' naming convention
  README.md
  docs/Config.md
  pkg/config/app_config.go
  pkg/config/user_config.go
  pkg/gui/controllers/helpers/window_arrangement_helper.go
  pkg/gui/controllers/screen_mode_actions.go
  pkg/gui/gui.go
  pkg/gui/types/common.go
  schema/config.json
Labels: maintenance, blocks-release

#4146 Cut a new release automatically each month
  .github/workflows/release.yml
Labels: maintenance

#4130 Add ability to configure branch color patterns using regex
  docs/Config.md
  pkg/config/user_config.go
  pkg/gui/gui.go
  pkg/gui/presentation/branches.go
  pkg/gui/presentation/branches_test.go
  pkg/i18n/english.go
  schema/config.json
Labels: enhancement

#4131 Collapse/uncollapse all files in tree
  docs/Config.md
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/config/user_config.go
  pkg/gui/controllers/commits_files_controller.go
  pkg/gui/controllers/files_controller.go
  pkg/gui/filetree/collapsed_paths.go
  pkg/gui/filetree/commit_file_tree.go
  pkg/gui/filetree/commit_file_tree_view_model.go
  pkg/gui/filetree/file_tree.go
  pkg/gui/filetree/file_tree_view_model.go
  pkg/i18n/english.go
  pkg/integration/tests/file/collapse_expand.go
  pkg/integration/tests/test_list.go
  schema/config.json
Labels: enhancement

#4167 Improve undo action to restore files upon undoing a commit
  pkg/gui/controllers/undo_controller.go
  pkg/i18n/english.go
  pkg/integration/tests/test_list.go
  pkg/integration/tests/undo/undo_commit.go
Labels: enhancement

#4178 Bump tcell to fix broken deployment
  go.mod
  go.sum
  vendor/github.com/gdamore/tcell/v2/attr.go
  vendor/github.com/gdamore/tcell/v2/tscreen.go
  vendor/modules.txt
Labels: maintenance

#4185 Add '--' to 'git rev-list' to disambiguate branch name from path
  pkg/commands/git_commands/branch.go
Labels: bug

#4182 Fix adding blank line at end of commit message
  go.mod
  go.sum
  pkg/gui/controllers/helpers/confirmation_helper.go
  pkg/gui/patch_exploring/state.go
  pkg/utils/lines.go
  pkg/utils/lines_test.go
  vendor/github.com/jesseduffield/gocui/view.go
  vendor/modules.txt
Labels: bug

#4214 Fix checking out a different branch while pushing a branch for the first time
  pkg/commands/git_commands/sync.go
  pkg/commands/git_commands/sync_test.go
  pkg/gui/controllers/sync_controller.go
Labels: bug

#4204 Expose {{.SelectedCommitRange}} to custom commands
  docs/Custom_Command_Keybindings.md
  pkg/gui/services/custom_commands/session_state_loader.go
  pkg/integration/tests/custom_commands/selected_commit_range.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4215 Show background fetch status in bottom line
  pkg/gui/background.go
Labels: enhancement

#4218 Support copying tags to clipboard
  docs/keybindings/Keybindings_en.md
  docs/keybindings/Keybindings_ja.md
  docs/keybindings/Keybindings_ko.md
  docs/keybindings/Keybindings_nl.md
  docs/keybindings/Keybindings_pl.md
  docs/keybindings/Keybindings_ru.md
  docs/keybindings/Keybindings_zh-CN.md
  docs/keybindings/Keybindings_zh-TW.md
  pkg/gui/controllers/basic_commits_controller.go
  pkg/gui/keybindings.go
  pkg/i18n/english.go
  pkg/integration/tests/commit/copy_tag_to_clipboard.go
  pkg/integration/tests/tag/copy_to_clipboard.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4217 Add option to delete local and remote tag
  pkg/gui/controllers/tags_controller.go
  pkg/i18n/english.go
  pkg/integration/components/shell.go
  pkg/integration/tests/tag/delete_local_and_remote.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4223 Fix flicker when showing backround fetch status
  pkg/gui/background.go
  pkg/gui/controllers/helpers/app_status_helper.go
Labels: ignore-for-release

#4222 Show confirmation menu when trying to amend changes while there are conflicts
  pkg/gui/controllers/files_controller.go
  pkg/gui/controllers/helpers/merge_and_rebase_helper.go
  pkg/i18n/english.go
  pkg/integration/tests/commit/amend_when_there_are_conflicts_and_amend.go
  pkg/integration/tests/commit/amend_when_there_are_conflicts_and_cancel.go
  pkg/integration/tests/commit/amend_when_there_are_conflicts_and_continue.go
  pkg/integration/tests/commit/shared.go
  pkg/integration/tests/test_list.go
Labels: enhancement

#4210 Improve error reporting on config migration
  pkg/config/app_config.go
Labels: enhancement
